
int _aid_list_add(uint8_t * mac);
int _aid_list_delete(uint8_t * mac);
void apm_assoc_req_handler(rxu_mgt_ind * param, _Bool is_reassoc);
void apm_auth_handler(rxu_mgt_ind * param);
void apm_bcn_set(void);
void apm_beacon_handler(rxu_mgt_ind * param);
void apm_bss_config_push(void * param);
void apm_deauth_handler(rxu_mgt_ind * param);
void apm_disassoc_handler(rxu_mgt_ind * param);
_Bool apm_embedded_enabled(vif_info_tag * vif);
void apm_probe_req_handler(rxu_mgt_ind * param);
void apm_send_mlme(vif_info_tag * vif, uint16_t fctl, mac_addr * ra, cfm_func_ptr * cfm_func, void * env, uint16_t status_code);
void apm_send_next_bss_param(void);
void apm_set_bss_param(void);
void apm_sta_add(uint8_t sta_idx);
void apm_sta_delete(uint8_t sta_idx, uint8_t * mac);
void apm_sta_fw_delete(uint8_t sta_idx);
void apm_sta_remove(uint8_t vif_idx, uint8_t sta_idx);
void apm_start_cfm(uint8_t status);
void apm_stop(vif_info_tag * vif);
void apm_tx_cfm_handler(void * env, uint32_t status);
_Bool apm_tx_int_ps_check(txdesc * txdesc);
void apm_tx_int_ps_clear(vif_info_tag * vif, uint8_t sta_idx);
txdesc * apm_tx_int_ps_get_postpone(vif_info_tag * vif, sta_info_tag * sta, int * stop);
void apm_tx_int_ps_postpone(txdesc * txdesc, sta_info_tag * sta);
