// bl602_demo_wifi_stack.c
// Generated by decompiling bl602_demo_wifi.elf
// using Reko decompiler version 0.9.3.0.

#include "bl602_demo_wifi.h"

Eq_2 g_t42041FF0 = 
	{
		0x00
	};
Eq_2 g_t42041FF4 = 
	{
		0x00
	};
Eq_2 g_t42041FF8 = 
	{
		0x00
	};
Eq_2 g_t42041FFC = 
	{
		0x00
	};
