// bl602_demo_wifi_data.c
// Generated by decompiling bl602_demo_wifi.elf
// using Reko decompiler version 0.9.3.0.

#include "bl602_demo_wifi.h"

// 4200C498: void AON_Power_On_BG()
void AON_Power_On_BG()
{
	(*(<anonymous> **) 0x21010828)();
}

// 4200C4A2: void AON_Power_Off_BG()
void AON_Power_Off_BG()
{
	(*(<anonymous> **) 553715756)();
}

// 4200C4AC: void AON_Power_On_LDO11_SOC()
void AON_Power_On_LDO11_SOC()
{
	(*(<anonymous> **) 0x21010830)();
}

// 4200C4B6: void AON_Power_Off_LDO11_SOC()
void AON_Power_Off_LDO11_SOC()
{
	(*(<anonymous> **) 553715764)();
}

// 4200C4C0: void AON_Power_On_LDO15_RF()
void AON_Power_On_LDO15_RF()
{
	(*(<anonymous> **) 0x21010838)();
}

// 4200C4CA: void AON_Power_Off_LDO15_RF()
void AON_Power_Off_LDO15_RF()
{
	(*(<anonymous> **) 553715772)();
}

// 4200C4D4: void AON_Power_On_SFReg()
void AON_Power_On_SFReg()
{
	(*(<anonymous> **) 0x21010840)();
}

// 4200C4DE: void AON_Power_Off_SFReg()
void AON_Power_Off_SFReg()
{
	(*(<anonymous> **) 0x21010844)();
}

// 4200C4E8: void AON_LowPower_Enter_PDS0()
void AON_LowPower_Enter_PDS0()
{
	(*(<anonymous> **) 0x21010848)();
}

// 4200C4F2: void AON_LowPower_Exit_PDS0()
void AON_LowPower_Exit_PDS0()
{
	(*(<anonymous> **) 553715788)();
}

// 4200C4FC: void ASM_Delay_Us()
void ASM_Delay_Us()
{
	(*(<anonymous> **) 0x21010850)();
}

// 4200C506: void BL602_Delay_US()
void BL602_Delay_US()
{
	(*(<anonymous> **) 553715796)();
}

// 4200C510: void BL602_Delay_MS()
void BL602_Delay_MS()
{
	(*(<anonymous> **) 0x21010858)();
}

// 4200C51A: void BL602_MemCpy()
void BL602_MemCpy()
{
	(*(<anonymous> **) 0x2101085C)();
}

// 4200C524: void BL602_MemCpy4()
void BL602_MemCpy4()
{
	(*(<anonymous> **) 0x21010860)();
}

// 4200C52E: void BL602_MemCpy_Fast()
void BL602_MemCpy_Fast()
{
	(*(<anonymous> **) 553715812)();
}

// 4200C538: void BL602_MemSet()
void BL602_MemSet()
{
	(*(<anonymous> **) 0x21010868)();
}

// 4200C542: void BL602_MemSet4()
void BL602_MemSet4()
{
	(*(<anonymous> **) 0x2101086C)();
}

// 4200C54C: void BL602_MemCmp()
void BL602_MemCmp()
{
	(*(<anonymous> **) 0x21010870)();
}

// 4200C556: void EF_Ctrl_Sw_AHB_Clk_0()
// Called from:
//      EF_Ctrl_Read_TSEN_Trim
//      EF_Ctrl_Read_ADC_Gain_Trim
void EF_Ctrl_Sw_AHB_Clk_0()
{
	(*(<anonymous> **) 553715828)();
}

// 4200C560: void EF_Ctrl_Program_Efuse_0()
void EF_Ctrl_Program_Efuse_0()
{
	(*(<anonymous> **) 0x21010878)();
}

// 4200C56A: void EF_Ctrl_Load_Efuse_R0()
// Called from:
//      EF_Ctrl_Read_TSEN_Trim
//      EF_Ctrl_Read_ADC_Gain_Trim
void EF_Ctrl_Load_Efuse_R0()
{
	(*(<anonymous> **) 553715836)();
}

// 4200C574: void EF_Ctrl_Busy()
void EF_Ctrl_Busy()
{
	(*(<anonymous> **) 0x21010880)();
}

// 4200C57E: void EF_Ctrl_AutoLoad_Done()
void EF_Ctrl_AutoLoad_Done()
{
	(*(<anonymous> **) 0x21010884)();
}

// 4200C588: void EF_Ctrl_Clear()
void EF_Ctrl_Clear()
{
	(*(<anonymous> **) 0x21010894)();
}

// 4200C592: void GLB_SW_System_Reset()
void GLB_SW_System_Reset()
{
	(*(<anonymous> **) 553715900)();
}

// 4200C59C: void GLB_SW_CPU_Reset()
void GLB_SW_CPU_Reset()
{
	(*(<anonymous> **) 0x210108C0)();
}

// 4200C5A6: void GLB_SW_POR_Reset()
void GLB_SW_POR_Reset()
{
	(*(<anonymous> **) 0x210108C4)();
}

// 4200C5B0: void GLB_Select_Internal_Flash()
void GLB_Select_Internal_Flash()
{
	(*(<anonymous> **) 0x210108C8)();
}

// 4200C5BA: void GLB_Select_External_Flash()
void GLB_Select_External_Flash()
{
	(*(<anonymous> **) 0x210108CC)();
}

// 4200C5C4: void GLB_Deswap_Flash_Pin()
void GLB_Deswap_Flash_Pin()
{
	(*(<anonymous> **) 0x210108D0)();
}

// 4200C5CE: void GLB_Swap_Flash_Pin()
void GLB_Swap_Flash_Pin()
{
	(*(<anonymous> **) 0x210108D4)();
}

// 4200C5D8: void GLB_GPIO_Init()
void GLB_GPIO_Init()
{
	(*(<anonymous> **) 0x210108D8)();
}

// 4200C5E2: void GLB_GPIO_OUTPUT_Enable()
void GLB_GPIO_OUTPUT_Enable()
{
	(*(<anonymous> **) 553715932)();
}

// 4200C5EC: void GLB_GPIO_OUTPUT_Disable()
void GLB_GPIO_OUTPUT_Disable()
{
	(*(<anonymous> **) 0x210108E0)();
}

// 4200C5F6: void GLB_GPIO_Set_HZ()
void GLB_GPIO_Set_HZ()
{
	(*(<anonymous> **) 0x210108E4)();
}

// 4200C600: void GLB_GPIO_Get_Fun()
void GLB_GPIO_Get_Fun()
{
	(*(<anonymous> **) 0x210108E8)();
}

// 4200C60A: void HBN_Mode_Enter()
void HBN_Mode_Enter()
{
	(*(<anonymous> **) 0x210108EC)();
}

// 4200C614: void HBN_Power_Down_Flash()
void HBN_Power_Down_Flash()
{
	(*(<anonymous> **) 0x210108F0)();
}

// 4200C61E: void HBN_Enable()
void HBN_Enable()
{
	(*(<anonymous> **) 553715956)();
}

// 4200C628: void HBN_Reset()
void HBN_Reset()
{
	(*(<anonymous> **) 0x210108F8)();
}

// 4200C632: void HBN_Set_Ldo11_Aon_Vout()
void HBN_Set_Ldo11_Aon_Vout()
{
	(*(<anonymous> **) 0x210108FC)();
}

// 4200C63C: void HBN_Set_Ldo11_Rt_Vout()
void HBN_Set_Ldo11_Rt_Vout()
{
	(*(<anonymous> **) 0x21010900)();
}

// 4200C646: void HBN_Set_Ldo11_Soc_Vout()
void HBN_Set_Ldo11_Soc_Vout()
{
	(*(<anonymous> **) 0x21010904)();
}

// 4200C650: void HBN_Hw_Pu_Pd_Cfg()
void HBN_Hw_Pu_Pd_Cfg()
{
	(*(<anonymous> **) 0x21010924)();
}

// 4200C65A: void HBN_Pin_WakeUp_Mask()
void HBN_Pin_WakeUp_Mask()
{
	(*(<anonymous> **) 0x21010928)();
}

// 4200C664: void HBN_GPIO7_Dbg_Pull_Cfg()
void HBN_GPIO7_Dbg_Pull_Cfg()
{
	(*(<anonymous> **) 0x2101092C)();
}

// 4200C66E: void HBN_Set_Embedded_Flash_Pullup()
void HBN_Set_Embedded_Flash_Pullup()
{
	(*(<anonymous> **) 0x21010930)();
}

// 4200C678: void L1C_Set_Wrap()
void L1C_Set_Wrap()
{
	(*(<anonymous> **) 0x21010934)();
}

// 4200C682: void L1C_Set_Way_Disable()
void L1C_Set_Way_Disable()
{
	(*(<anonymous> **) 0x21010938)();
}

// 4200C68C: void L1C_IROM_2T_Access_Set()
void L1C_IROM_2T_Access_Set()
{
	(*(<anonymous> **) 0x2101093C)();
}

// 4200C696: void PDS_Reset()
void PDS_Reset()
{
	(*(<anonymous> **) 0x21010940)();
}

// 4200C6A0: void PDS_Force_Config()
void PDS_Force_Config()
{
	(*(<anonymous> **) 0x21010948)();
}

// 4200C6AA: void PDS_RAM_Config()
void PDS_RAM_Config()
{
	(*(<anonymous> **) 0x2101094C)();
}

// 4200C6B4: void PDS_Default_Level_Config()
void PDS_Default_Level_Config()
{
	(*(<anonymous> **) 0x21010950)();
}

// 4200C6BE: void SEC_Eng_Turn_On_Sec_Ring()
void SEC_Eng_Turn_On_Sec_Ring()
{
	(*(<anonymous> **) 0x21010978)();
}

// 4200C6C8: void SEC_Eng_Turn_Off_Sec_Ring()
void SEC_Eng_Turn_Off_Sec_Ring()
{
	(*(<anonymous> **) 0x2101097C)();
}

// 4200C6D2: void SFlash_Init()
void SFlash_Init()
{
	(*(<anonymous> **) 0x21010980)();
}

// 4200C6DC: void SFlash_SetSPIMode()
void SFlash_SetSPIMode()
{
	(*(<anonymous> **) 0x21010984)();
}

// 4200C6E6: void SFlash_Read_Reg()
void SFlash_Read_Reg()
{
	(*(<anonymous> **) 0x21010988)();
}

// 4200C6F0: void SFlash_Write_Reg()
void SFlash_Write_Reg()
{
	(*(<anonymous> **) 0x2101098C)();
}

// 4200C6FA: void SFlash_Busy()
void SFlash_Busy()
{
	(*(<anonymous> **) 0x21010990)();
}

// 4200C704: void SFlash_Write_Enable()
void SFlash_Write_Enable()
{
	(*(<anonymous> **) 553716116)();
}

// 4200C70E: void SFlash_Qspi_Enable()
void SFlash_Qspi_Enable()
{
	(*(<anonymous> **) 0x21010998)();
}

// 4200C718: void SFlash_Volatile_Reg_Write_Enable()
void SFlash_Volatile_Reg_Write_Enable()
{
	(*(<anonymous> **) 0x2101099C)();
}

// 4200C722: void SFlash_Chip_Erase()
void SFlash_Chip_Erase()
{
	(*(<anonymous> **) 0x210109A0)();
}

// 4200C72C: void SFlash_Sector_Erase()
void SFlash_Sector_Erase()
{
	(*(<anonymous> **) 0x210109A4)();
}

// 4200C736: void SFlash_Blk32_Erase()
void SFlash_Blk32_Erase()
{
	(*(<anonymous> **) 553716136)();
}

// 4200C740: void SFlash_Blk64_Erase()
void SFlash_Blk64_Erase()
{
	(*(<anonymous> **) 0x210109AC)();
}

// 4200C74A: void SFlash_Erase()
void SFlash_Erase()
{
	(*(<anonymous> **) 0x210109B0)();
}

// 4200C754: void SFlash_Program()
void SFlash_Program()
{
	(*(<anonymous> **) 0x210109B4)();
}

// 4200C75E: void SFlash_GetUniqueId()
void SFlash_GetUniqueId()
{
	(*(<anonymous> **) 553716152)();
}

// 4200C768: void SFlash_GetJedecId()
void SFlash_GetJedecId()
{
	(*(<anonymous> **) 553716156)();
}

// 4200C772: void SFlash_GetDeviceId()
void SFlash_GetDeviceId()
{
	(*(<anonymous> **) 0x210109C0)();
}

// 4200C77C: void SFlash_Powerdown()
void SFlash_Powerdown()
{
	(*(<anonymous> **) 0x210109C4)();
}

// 4200C786: void SFlash_Releae_Powerdown()
void SFlash_Releae_Powerdown()
{
	(*(<anonymous> **) 0x210109C8)();
}

// 4200C790: void SFlash_SetBurstWrap()
void SFlash_SetBurstWrap()
{
	(*(<anonymous> **) 0x210109CC)();
}

// 4200C79A: void SFlash_DisableBurstWrap()
void SFlash_DisableBurstWrap()
{
	(*(<anonymous> **) 0x210109D0)();
}

// 4200C7A4: void SFlash_Software_Reset()
void SFlash_Software_Reset()
{
	(*(<anonymous> **) 0x210109D4)();
}

// 4200C7AE: void SFlash_Reset_Continue_Read()
void SFlash_Reset_Continue_Read()
{
	(*(<anonymous> **) 0x210109D8)();
}

// 4200C7B8: void SFlash_Set_IDbus_Cfg()
void SFlash_Set_IDbus_Cfg()
{
	(*(<anonymous> **) 0x210109DC)();
}

// 4200C7C2: void SFlash_IDbus_Read_Enable()
void SFlash_IDbus_Read_Enable()
{
	(*(<anonymous> **) 0x210109E0)();
}

// 4200C7CC: void SFlash_Cache_Enable_Set()
void SFlash_Cache_Enable_Set()
{
	(*(<anonymous> **) 0x210109E4)();
}

// 4200C7D6: void SFlash_Cache_Flush()
void SFlash_Cache_Flush()
{
	(*(<anonymous> **) 0x210109E8)();
}

// 4200C7E0: void SFlash_Cache_Read_Enable()
void SFlash_Cache_Read_Enable()
{
	(*(<anonymous> **) 0x210109EC)();
}

// 4200C7EA: void SFlash_Cache_Hit_Count_Get()
void SFlash_Cache_Hit_Count_Get()
{
	(*(<anonymous> **) 0x210109F0)();
}

// 4200C7F4: void SFlash_Cache_Miss_Count_Get()
void SFlash_Cache_Miss_Count_Get()
{
	(*(<anonymous> **) 0x210109F4)();
}

// 4200C7FE: void SFlash_Cache_Read_Disable()
void SFlash_Cache_Read_Disable()
{
	(*(<anonymous> **) 0x210109F8)();
}

// 4200C808: void SFlash_Read()
void SFlash_Read()
{
	(*(<anonymous> **) 0x210109FC)();
}

// 4200C812: void SFlash_Read_Reg_With_Cmd()
void SFlash_Read_Reg_With_Cmd()
{
	(*(<anonymous> **) 0x21010A00)();
}

// 4200C81C: void SFlash_Write_Reg_With_Cmd()
void SFlash_Write_Reg_With_Cmd()
{
	(*(<anonymous> **) 0x21010A04)();
}

// 4200C826: void SF_Cfg_Init_Ext_Flash_Gpio()
void SF_Cfg_Init_Ext_Flash_Gpio()
{
	(*(<anonymous> **) 0x21010A0C)();
}

// 4200C830: void SF_Cfg_Init_Internal_Flash_Gpio()
void SF_Cfg_Init_Internal_Flash_Gpio()
{
	(*(<anonymous> **) 0x21010A10)();
}

// 4200C83A: void SF_Cfg_Deinit_Ext_Flash_Gpio()
void SF_Cfg_Deinit_Ext_Flash_Gpio()
{
	(*(<anonymous> **) 0x21010A14)();
}

// 4200C844: void SF_Cfg_Restore_GPIO17_Fun()
void SF_Cfg_Restore_GPIO17_Fun()
{
	(*(<anonymous> **) 0x21010A18)();
}

// 4200C84E: void SF_Cfg_Get_Flash_Cfg_Need_Lock()
void SF_Cfg_Get_Flash_Cfg_Need_Lock()
{
	(*(<anonymous> **) 0x21010A1C)();
}

// 4200C858: void SF_Cfg_Init_Flash_Gpio()
void SF_Cfg_Init_Flash_Gpio()
{
	(*(<anonymous> **) 0x21010A20)();
}

// 4200C862: void SF_Cfg_Flash_Identify()
void SF_Cfg_Flash_Identify()
{
	(*(<anonymous> **) 0x21010A24)();
}

// 4200C86C: void SF_Ctrl_Enable()
void SF_Ctrl_Enable()
{
	(*(<anonymous> **) 0x21010A28)();
}

// 4200C876: void SF_Ctrl_Select_Pad()
void SF_Ctrl_Select_Pad()
{
	(*(<anonymous> **) 0x21010A2C)();
}

// 4200C880: void SF_Ctrl_Set_Owner()
void SF_Ctrl_Set_Owner()
{
	(*(<anonymous> **) 0x21010A30)();
}

// 4200C88A: void SF_Ctrl_Disable()
void SF_Ctrl_Disable()
{
	(*(<anonymous> **) 0x21010A34)();
}

// 4200C894: void SF_Ctrl_AES_Enable_BE()
void SF_Ctrl_AES_Enable_BE()
{
	(*(<anonymous> **) 0x21010A38)();
}

// 4200C89E: void SF_Ctrl_AES_Enable_LE()
void SF_Ctrl_AES_Enable_LE()
{
	(*(<anonymous> **) 0x21010A3C)();
}

// 4200C8A8: void SF_Ctrl_AES_Set_Region()
void SF_Ctrl_AES_Set_Region()
{
	(*(<anonymous> **) 0x21010A40)();
}

// 4200C8B2: void SF_Ctrl_AES_Set_Key()
void SF_Ctrl_AES_Set_Key()
{
	(*(<anonymous> **) 0x21010A44)();
}

// 4200C8BC: void SF_Ctrl_AES_Set_Key_BE()
void SF_Ctrl_AES_Set_Key_BE()
{
	(*(<anonymous> **) 0x21010A48)();
}

// 4200C8C6: void SF_Ctrl_AES_Set_IV()
void SF_Ctrl_AES_Set_IV()
{
	(*(<anonymous> **) 0x21010A4C)();
}

// 4200C8D0: void SF_Ctrl_AES_Set_IV_BE()
void SF_Ctrl_AES_Set_IV_BE()
{
	(*(<anonymous> **) 0x21010A50)();
}

// 4200C8DA: void SF_Ctrl_AES_Enable()
void SF_Ctrl_AES_Enable()
{
	(*(<anonymous> **) 0x21010A54)();
}

// 4200C8E4: void SF_Ctrl_AES_Disable()
void SF_Ctrl_AES_Disable()
{
	(*(<anonymous> **) 0x21010A58)();
}

// 4200C8EE: void SF_Ctrl_Set_Flash_Image_Offset()
void SF_Ctrl_Set_Flash_Image_Offset()
{
	(*(<anonymous> **) 553716316)();
}

// 4200C8F8: void SF_Ctrl_Get_Flash_Image_Offset()
void SF_Ctrl_Get_Flash_Image_Offset()
{
	(*(<anonymous> **) 0x21010A60)();
}

// 4200C902: void SF_Ctrl_Select_Clock()
void SF_Ctrl_Select_Clock()
{
	(*(<anonymous> **) 0x21010A64)();
}

// 4200C90C: void SF_Ctrl_SendCmd()
void SF_Ctrl_SendCmd()
{
	(*(<anonymous> **) 0x21010A68)();
}

// 4200C916: void SF_Ctrl_Icache_Set()
void SF_Ctrl_Icache_Set()
{
	(*(<anonymous> **) 553716332)();
}

// 4200C920: void SF_Ctrl_Icache2_Set()
void SF_Ctrl_Icache2_Set()
{
	(*(<anonymous> **) 0x21010A70)();
}

// 4200C92A: void SF_Ctrl_GetBusyState()
void SF_Ctrl_GetBusyState()
{
	(*(<anonymous> **) 0x21010A74)();
}

// 4200C934: void SF_Ctrl_Is_AES_Enable()
void SF_Ctrl_Is_AES_Enable()
{
	(*(<anonymous> **) 0x21010A78)();
}

// 4200C93E: void SF_Ctrl_Get_Clock_Delay()
void SF_Ctrl_Get_Clock_Delay()
{
	(*(<anonymous> **) 0x21010A7C)();
}

// 4200C948: void SF_Ctrl_Set_Clock_Delay()
void SF_Ctrl_Set_Clock_Delay()
{
	(*(<anonymous> **) 0x21010A80)();
}

// 4200C952: void XIP_SFlash_State_Save()
void XIP_SFlash_State_Save()
{
	(*(<anonymous> **) 553716356)();
}

// 4200C95C: void XIP_SFlash_State_Restore()
void XIP_SFlash_State_Restore()
{
	(*(<anonymous> **) 0x21010A88)();
}

// 4200C966: void XIP_SFlash_Erase_Need_Lock()
void XIP_SFlash_Erase_Need_Lock()
{
	(*(<anonymous> **) 0x21010A8C)();
}

// 4200C970: void XIP_SFlash_Write_Need_Lock()
void XIP_SFlash_Write_Need_Lock()
{
	(*(<anonymous> **) 0x21010A90)();
}

// 4200C97A: void XIP_SFlash_Read_Need_Lock()
void XIP_SFlash_Read_Need_Lock()
{
	(*(<anonymous> **) 0x21010A94)();
}

// 4200C984: void XIP_SFlash_GetJedecId_Need_Lock()
void XIP_SFlash_GetJedecId_Need_Lock()
{
	(*(<anonymous> **) 553716376)();
}

// 4200C98E: void XIP_SFlash_GetDeviceId_Need_Lock()
void XIP_SFlash_GetDeviceId_Need_Lock()
{
	(*(<anonymous> **) 0x21010A9C)();
}

// 4200C998: void XIP_SFlash_GetUniqueId_Need_Lock()
void XIP_SFlash_GetUniqueId_Need_Lock()
{
	(*(<anonymous> **) 0x21010AA0)();
}

// 4200C9A2: void XIP_SFlash_Read_Via_Cache_Need_Lock()
void XIP_SFlash_Read_Via_Cache_Need_Lock()
{
	(*(<anonymous> **) 0x21010AA4)();
}

// 4200C9AC: void XIP_SFlash_Read_With_Lock()
void XIP_SFlash_Read_With_Lock()
{
	(*(<anonymous> **) 0x21010AA8)();
}

// 4200C9B6: void XIP_SFlash_Write_With_Lock()
void XIP_SFlash_Write_With_Lock()
{
	(*(<anonymous> **) 0x21010AAC)();
}

// 4200C9C0: void XIP_SFlash_Erase_With_Lock()
void XIP_SFlash_Erase_With_Lock()
{
	(*(<anonymous> **) 0x21010AB0)();
}

// 4200C9CA: void XIP_SFlash_Opt_Enter()
void XIP_SFlash_Opt_Enter()
{
	(*(<anonymous> **) 0x21010AB4)();
}

// 4200C9D4: void XIP_SFlash_Opt_Exit()
void XIP_SFlash_Opt_Exit()
{
	(*(<anonymous> **) 0x21010AB8)();
}

// 4200C9DE: void BFLB_Soft_CRC32()
void BFLB_Soft_CRC32()
{
	(*(<anonymous> **) 0x21010ABC)();
}

// 4200C9E8: void ADC_Trim_TSEN(Register (ptr32 word16) a0, Register ui32 a4, Register word32 s4, Register word32 s5, Stack word32 dwArg04, Stack word32 dwArgA4)
void ADC_Trim_TSEN(word16 * a0, ui32 a4, word32 s4, word32 s5, word32 dwArg04, word32 dwArgA4)
{
	word16 * s2_106 = a0;
	uint32 a0_24 = EF_Ctrl_Read_TSEN_Trim(a4);
	if (a0_24 << 0x12 >= 0x00)
		return;
	uint32 a0_39 = (a0_24 & 0x00FFFFFF) << 16;
	uint32 a0_107 = a0_39 >> 16;
	ui32 a5_43 = EF_Ctrl_Get_Trim_Parity();
	if ((a0_24 >> 0x0C & 0x01) != a0_39 >> 16)
		return;
	*a0 = (word16) (a5_43 & 0x00FFFFFF);
	ui32 s1_108 = a5_43 & 0x04000000;
	word32 s0_50 = 0x00;
	if ((a5_43 & 0x04000000) == 0x00)
	{
		*(ui32 *) 0x4001090C = *(int32 *) 0x4000F90C & ~0x00080000;
		word32 a4_54 = ~0x00080000;
		int32 s3_109 = 50;
		do
		{
			word32 s0_73;
			ui32 s3_75;
			word32 fs1_87;
			word32 fs0_88;
			word32 fa0_89;
			g_t23052E86();
			s3_109 = s3_75 & 0x00FF;
			s0_50 = s0_73 + a0_107;
		} while ((s3_75 & 0x00FF) != 0x00);
		*(ui32 *) 0x4001090C = *(int32 *) 0x4000F90C | 0x00080000;
		word32 a4_112 = 0x40010000;
		int32 s0_102 = 50;
		do
		{
			ui32 s0_118;
			word32 s1_119;
			word32 fs1_132;
			word32 fs0_133;
			word32 fa0_134;
			g_t23052E86();
			s0_102 = s0_118 & 0x00FF;
			s1_108 = s1_119 + a0_107;
		} while ((s0_118 & 0x00FF) != 0x00);
		word32 s2_146;
		word32 a0_147;
		word32 s0_149;
		word32 s1_150;
		word32 s3_151;
		word32 a1_160;
		word32 a4_162;
		word32 fs1_163;
		g_t23070708();
		word32 s2_172;
		word32 a0_173;
		word32 s0_175;
		word32 s1_176;
		word32 s3_177;
		word32 s4_178;
		word32 s5_179;
		word32 a4_188;
		g_t23070708();
		word32 s2_198;
		word32 a0_199;
		word32 s0_201;
		word32 s1_202;
		word32 s3_203;
		word32 s4_204;
		word32 s5_205;
		word32 a1_212;
		word32 a4_214;
		g_t2306F140();
		word32 s2_225;
		word32 a0_226;
		word32 s0_228;
		word32 s1_229;
		word32 s3_230;
		word32 a1_239;
		word32 a4_241;
		word32 fs0_243;
		g_t2306F8DC();
		word32 s2_251;
		word32 a0_252;
		word32 s0_254;
		word32 s1_255;
		word32 s3_256;
		word32 s4_257;
		word32 s5_258;
		word32 a4_267;
		g_t23070708();
		word32 s2_277;
		word32 a0_278;
		word32 s0_280;
		word32 s1_281;
		word32 s3_282;
		word32 s4_283;
		word32 s5_284;
		word32 a1_291;
		word32 a4_293;
		g_t2306F140();
		word32 s2_304;
		word32 a0_305;
		word32 s0_307;
		word32 s1_308;
		word32 s3_309;
		word32 s4_310;
		word32 s5_311;
		word32 a4_320;
		g_t2306DAA4();
		word32 s2_330;
		word32 a0_331;
		word32 s0_333;
		word32 s1_334;
		word32 s3_335;
		word32 s4_336;
		word32 s5_337;
		word32 a4_346;
		g_t2306DAA4();
		word16 * s2_353;
		word32 fs1_370;
		real32 fs0_371;
		real32 fa0_372;
		g_t23070818();
		real32 fa0_374 = fa0_372 + fs0_371;
		*s2_353 = (word16) (uint32) fa0_374;
	}
}

// 4200CB5C: void ADC_Gain_Trim(Register (ptr32 Eq_362695) a4, Stack word32 dwArg14, Stack word32 dwArgB4, Stack word32 dwArg0128)
void ADC_Gain_Trim(struct Eq_362695 * a4, word32 dwArg14, word32 dwArgB4, word32 dwArg0128)
{
	word32 a4_21;
	uint32 a0_18 = EF_Ctrl_Read_ADC_Gain_Trim(a4, out a4_21);
	if (a0_18 << 0x12 < 0x00)
	{
		EF_Ctrl_Get_Trim_Parity();
		if ((a0_18 >> 0x0C & 0x01) == (word32) ((word16) (a0_18 & 0x00FFFFFF)))
		{
			word32 a4_112;
			word32 s4_103;
			word32 s3_102;
			word32 s2_101;
			word32 s1_100;
			word32 s0_163;
			g_b4200D96C = 0x01;
			g_w4200D96E = 0x01;
			if (false)
			{
				word32 s0_121;
				word32 s1_122;
				word32 s2_123;
				word32 s3_124;
				word32 s4_125;
				word32 a4_134;
				g_t23070708();
				word32 s0_142;
				word32 s1_143;
				word32 s2_144;
				word32 s3_145;
				word32 s4_146;
				word32 a4_155;
				g_t2306F140();
				word32 a1_173;
				word32 fa0_174;
				g_t2306DAA4();
			}
			else
			{
				word32 s0_55;
				word32 s1_56;
				word32 s2_57;
				word32 s3_58;
				word32 s4_59;
				word32 a4_68;
				g_t23070708();
				word32 a0_74;
				word32 s0_76;
				word32 s1_77;
				word32 s2_78;
				word32 s3_79;
				word32 s4_80;
				word32 a1_86;
				word32 a4_89;
				g_t2306F140();
				word32 a1_109;
				word32 fa0_110;
				g_t2306F8DC();
			}
			struct Eq_362772 * a0_187;
			real32 s0_189;
			word32 a1_199;
			word32 fa0_200;
			g_t23070818();
			a0_187->r0004 = s0_189;
l4200CB7A:
			0x00 = dwArg0128;
			return;
		}
	}
	goto l4200CB7A;
}

// 4200CCE4: Register word32 EF_Ctrl_Read_TSEN_Trim(Register ui32 a4)
// Called from:
//      ADC_Trim_TSEN
word32 EF_Ctrl_Read_TSEN_Trim(ui32 a4)
{
	EF_Ctrl_Sw_AHB_Clk_0();
	EF_Ctrl_Load_Efuse_R0();
	word32 a0_18 = *(a4 & 0x01);
	word32 * a4_22 = a4 & 0x01 & ~0x02000000 | (a4 & 0x01) << 0x0D;
	*a4_22 = a0_18;
	word32 * a5_33 = (a4_22 & 0xFF000000 | 0x0FFF) & ~0x01000000 | 0x01000000;
	*a5_33 = a0_18;
	*(a5_33 & ~0x04000000) = a0_18;
	return a0_18;
}

// 4200CD40: Register word32 EF_Ctrl_Read_ADC_Gain_Trim(Register (ptr32 Eq_362695) a4, Register out Eq_362704 a4Out)
// Called from:
//      ADC_Gain_Trim
word32 EF_Ctrl_Read_ADC_Gain_Trim(struct Eq_362695 * a4, union Eq_362704 & a4Out)
{
	EF_Ctrl_Sw_AHB_Clk_0();
	EF_Ctrl_Load_Efuse_R0();
	word32 * a5_14 = a4->ptr0078;
	ui32 a4_29 = a4 >> 0x0E & 0x01;
	word32 a0_15 = *a5_14;
	*(((a5_14 & 0xFF000000 | (a4 << 0x13) >> 20) & ~0x01000000 | (a4 >> 0x0D & 0x01) << 0x0C) & ~0x02000000 | a4_29 << 0x0D) = a0_15;
	a4Out = a4_29 << 0x0D;
	return a0_15;
}

// 4200CD86: void AON_Power_On_MBG()
void AON_Power_On_MBG()
{
	(*(<anonymous> **) 0x21010810)();
}

// 4200CD90: void AON_Power_Off_MBG()
void AON_Power_Off_MBG()
{
	(*(<anonymous> **) 0x21010814)();
}

// 4200CD9A: void AON_Power_On_XTAL()
void AON_Power_On_XTAL()
{
	(*(<anonymous> **) 0x21010818)();
}

// 4200CDA4: void AON_Set_Xtal_CapCode()
void AON_Set_Xtal_CapCode()
{
	(*(<anonymous> **) 0x2101081C)();
}

// 4200CDAE: void AON_Get_Xtal_CapCode()
void AON_Get_Xtal_CapCode()
{
	(*(<anonymous> **) 0x21010820)();
}

// 4200CDB8: void AON_Power_Off_XTAL()
void AON_Power_Off_XTAL()
{
	(*(<anonymous> **) 0x21010824)();
}

// 4200CDC2: Register word32 EF_Ctrl_Get_Trim_Parity()
// Called from:
//      ADC_Trim_TSEN
//      ADC_Gain_Trim
word32 EF_Ctrl_Get_Trim_Parity()
{
	word32 a5_7;
	(*(<anonymous> **) 0x21010888)();
	return a5_7;
}

// 4200CDCC: void EF_Ctrl_Read_RC32M_Trim()
void EF_Ctrl_Read_RC32M_Trim()
{
	(*(<anonymous> **) 0x2101088C)();
}

// 4200CDD6: void EF_Ctrl_Read_RC32K_Trim()
void EF_Ctrl_Read_RC32K_Trim()
{
	(*(<anonymous> **) 0x21010890)();
}

// 4200CDE0: void GLB_Get_Root_CLK_Sel()
void GLB_Get_Root_CLK_Sel()
{
	(*(<anonymous> **) 0x21010898)();
}

// 4200CDEA: void GLB_Set_System_CLK_Div()
void GLB_Set_System_CLK_Div()
{
	(*(<anonymous> **) 553715868)();
}

// 4200CDF4: void GLB_Get_BCLK_Div()
void GLB_Get_BCLK_Div()
{
	(*(<anonymous> **) 0x210108A0)();
}

// 4200CDFE: void GLB_Get_HCLK_Div()
void GLB_Get_HCLK_Div()
{
	(*(<anonymous> **) 553715876)();
}

// 4200CE08: void Update_SystemCoreClockWith_XTAL()
void Update_SystemCoreClockWith_XTAL()
{
	(*(<anonymous> **) 0x210108A8)();
}

// 4200CE12: void GLB_Set_System_CLK()
void GLB_Set_System_CLK()
{
	(*(<anonymous> **) 553715884)();
}

// 4200CE1C: void System_Core_Clock_Update_From_RC32M()
void System_Core_Clock_Update_From_RC32M()
{
	(*(<anonymous> **) 0x210108B0)();
}

// 4200CE26: void GLB_Set_SF_CLK()
void GLB_Set_SF_CLK()
{
	(*(<anonymous> **) 0x210108B4)();
}

// 4200CE30: void GLB_Set_PKA_CLK_Sel()
void GLB_Set_PKA_CLK_Sel()
{
	(*(<anonymous> **) 0x210108B8)();
}

// 4200CE3A: void HBN_32K_Sel()
void HBN_32K_Sel()
{
	(*(<anonymous> **) 0x21010908)();
}

// 4200CE44: void HBN_Set_ROOT_CLK_Sel()
void HBN_Set_ROOT_CLK_Sel()
{
	(*(<anonymous> **) 0x2101090C)();
}

// 4200CE4E: void HBN_Power_On_Xtal_32K()
void HBN_Power_On_Xtal_32K()
{
	(*(<anonymous> **) 0x21010910)();
}

// 4200CE58: void HBN_Power_Off_Xtal_32K()
void HBN_Power_Off_Xtal_32K()
{
	(*(<anonymous> **) 0x21010914)();
}

// 4200CE62: void HBN_Power_On_RC32K()
void HBN_Power_On_RC32K()
{
	(*(<anonymous> **) 0x21010918)();
}

// 4200CE6C: void HBN_Power_Off_RC32K()
void HBN_Power_Off_RC32K()
{
	(*(<anonymous> **) 0x2101091C)();
}

// 4200CE76: void HBN_Trim_RC32K()
void HBN_Trim_RC32K()
{
	(*(<anonymous> **) 0x21010920)();
}

// 4200CE80: void PDS_Trim_RC32M()
void PDS_Trim_RC32M()
{
	(*(<anonymous> **) 0x21010954)();
}

// 4200CE8A: void PDS_Select_RC32M_As_PLL_Ref()
void PDS_Select_RC32M_As_PLL_Ref()
{
	(*(<anonymous> **) 553716056)();
}

// 4200CE94: void PDS_Select_XTAL_As_PLL_Ref()
void PDS_Select_XTAL_As_PLL_Ref()
{
	(*(<anonymous> **) 0x2101095C)();
}

// 4200CE9E: void PDS_Power_On_PLL()
void PDS_Power_On_PLL()
{
	(*(<anonymous> **) 0x21010960)();
}

// 4200CEA8: void PDS_Enable_PLL_All_Clks()
void PDS_Enable_PLL_All_Clks()
{
	(*(<anonymous> **) 0x21010964)();
}

// 4200CEB2: void PDS_Disable_PLL_All_Clks()
void PDS_Disable_PLL_All_Clks()
{
	(*(<anonymous> **) 0x21010968)();
}

// 4200CEBC: void PDS_Enable_PLL_Clk()
void PDS_Enable_PLL_Clk()
{
	(*(<anonymous> **) 0x2101096C)();
}

// 4200CEC6: void PDS_Disable_PLL_Clk()
void PDS_Disable_PLL_Clk()
{
	(*(<anonymous> **) 0x21010970)();
}

// 4200CED0: void PDS_Power_Off_PLL()
void PDS_Power_Off_PLL()
{
	(*(<anonymous> **) 0x21010974)();
}

Eq_5041 g_t4200CEDC = 
	{
		0x42020D66,
		0x00020A9A,
	};
byte g_a4200CEFC[5] = 
	{
		0x12,
		0x12,
		0x12,
		0x12,
		0x12,
	};
byte g_a4200CF04[] = 
	{
	};
byte g_a4200CF0C[] = 
	{
	};
uint16 g_a4200CF14[22] = 
	{
		~0x5914,
		42802,
		~0x5886,
		42944,
		0xA808,
		0xA84F,
		0xA896,
		~0x5722,
		43300,
		43371,
		43442,
		~0x5606,
		0xAA40,
		0xAA87,
		~0x5530,
		0xAB16,
		~0x54A2,
		0xABA4,
		44011,
		44082,
		44153,
		0x00,
	};
word16 g_w4200CF3C = 44153;
int32 g_dw4200CF40 = 0x14088889;
int32 g_dw4200CF64 = 0x14555555;
word32 g_dw4200CF94 = 0x00;
word32 g_dw4200CF98 = 0x00;
word32 g_dw4200CF9C = 0x00;
word32 g_dw4200CFA0 = 0x00;
word32 g_dw4200CFA4 = 0x00;
word32 g_dw4200CFA8 = 0x00;
word32 g_dw4200CFAC = 0x00;
word32 g_dw4200CFB0 = 0x00;
word32 g_dw4200CFB4 = 0x01;
word32 g_dw4200CFB8 = 8000000;
word32 g_dw4200CFBC = 0x01;
word32 g_dw4200CFC0 = 3000000;
word32 g_dw4200CFC4 = 0x01;
word32 g_dw4200CFC8 = 4292967296;
word32 g_dw4200CFCC = 0x01;
word32 g_dw4200CFD0 = 0xFF953040;
word32 g_dw4200CFD4 = 0x00;
word32 g_dw4200CFD8 = 0x00;
word32 g_dw4200CFDC = 0x00;
word32 g_dw4200CFE0 = 0x00;
word32 g_dw4200CFE4 = 0x00;
word32 g_dw4200CFE8 = 0x00;
word32 g_dw4200CFEC = 0x00;
word32 g_dw4200CFF0 = 0x00;
word32 g_dw4200CFF4 = 0x01;
word32 g_dw4200CFF8 = 8000000;
word32 g_dw4200CFFC = 0x01;
word32 g_dw4200D000 = ~0x003D08FF;
Eq_69636 g_t4200D004 = 
	{
		~0x04,
		0x0F,
	};
word32 g_dw4200D014 = 0x0F;
int32 g_dw4200D018 = 0x0033;
byte g_a4200D038[17] = 
	{
		252,
		~0x07,
		252,
		~0x07,
		252,
		~0x07,
		252,
		~0x07,
		252,
		~0x07,
		~0x04,
		~0x08,
		252,
		~0x07,
		~0x04,
		~0x08,
		0x01,
	};
Eq_2 g_t4200D08C = 
	{
		0x01
	};
Eq_111565 g_t4200D438 = 
	{
		0x00,
		0x00,
		
		{
			0x00
		},
		0x00,
	};
byte g_b4200D47A = 0x00;
byte g_b4200D47B = 0x00;
Eq_2 g_t4200D4A8 = 
	{
		0xC02B
	};
Eq_2 g_t4200D4AC = 
	{
		0xC02C
	};
Eq_2 g_t4200D4B0 = 
	{
		0x00
	};
Eq_2 g_t4200D4B4 = 
	{
		0x06
	};
Eq_2 g_t4200D4C0 = 
	{
		0x00
	};
word32 g_dw4200D4F0 = 0x00;
Eq_2 g_t4200D50C = 
	{
		0x00
	};
int32 g_dw4200D8F0 = 31;
byte g_b4200D8F4 = ~0x00;
Eq_2 g_t4200D904 = 
	{
		~0x00
	};
int32 g_dw4200D908 = 0x02CC;
int8 g_b4200D90C = -0x0080;
uint16 g_w4200D918 = 0xA6A0;
uint16 g_w4200D91A = 0xA6E0;
uint16 g_w4200D91C = 0xACE0;
uint16 g_w4200D91E = 0x0855;
uint16 g_w4200D924 = 0x05;
uint16 g_w4200D926 = 0x05;
uint16 g_w4200D928 = 0x05;
struct Eq_68109 * g_ptr4200D92C = &g_t42011F74;
Eq_2 g_t4200D934 = 
	{
		54700
	};
int32 g_dw4200D938 = 92;
int8 g_b4200D93C = -1;
int8 g_b4200D93D = -1;
uint16 g_w4200D948 = ~0x00;
byte g_b4200D94A = 0x01;
uint16 g_w4200D950 = 0xC000;
uint16 g_w4200D952 = 0xC000;
Eq_256667 g_t4200D954 = 
	{
		<code>,
		&g_t4200D954,
		0x01,
	};
Eq_2 g_t4200D960 = 
	{
		~0x00
	};
byte g_b4200D964 = 0x01;
Eq_2 g_t4200D968 = 
	{
		0x2800
	};
byte g_b4200D96C = 0x00;
word16 g_w4200D96E = 0x00;
byte g_b4200D974 = 0x03;
Eq_2 g_t4200D97C = 
	{
		0x08
	};
union Eq_2 * g_ptr4200D994 = &g_t4200D4C0;
Eq_2 g_t4200D9B8 = 
	{
		0x00
	};
Eq_2 g_t4200D9BC = 
	{
		0x00
	};
