// bl602_demo_wifi_boot2.c
// Generated by decompiling bl602_demo_wifi.elf
// using Reko decompiler version 0.9.3.0.

#include "bl602_demo_wifi.h"

byte g_b4200D9C8 = 0x00;
int32 g_dw4200D9CC = 0;
uint16 g_w4200D9D2 = 0x00;
Eq_2 g_t4200D9D4 = 
	{
		0x00
	};
Eq_2 g_t4200D9D8 = 
	{
		0x00
	};
word32 g_dw4200DC20 = 0x00;
byte g_b4200DC31 = 0x00;
