// bl602_demo_wifi_bss_0001.c
// Generated by decompiling bl602_demo_wifi.elf
// using Reko decompiler version 0.9.3.0.

#include "bl602_demo_wifi.h"

Eq_116288 g_t4201E000 = 
	{
		0x00,
	};
struct Eq_108944 * g_ptr4201E3D4 = null;
word32 g_dw4201E41C = 0x00;
Eq_99482 g_t4201E440 = 
	{
		0x00,
		0x00,
	};
byte g_b4201E448 = 0x00;
ui32 g_dw4201E44C = 0x00;
word32 g_dw4201E450 = 0x00;
word32 g_dw4201E454 = 0x00;
word16 g_w4201E4AE = 0x00;
int8 g_b4201E4C0 = 0;
word16 g_w4201E51E = 0x00;
word32 g_dw4201E520 = 0x00;
Eq_363216 g_a4201E6F2[] = 
	{
	};
word32 g_dw4201F3C8 = 0x00;
word32 g_dw4201F3CC = 0x00;
Eq_115169 g_t4201F448 = 
	{
		0,
	};
Eq_2 g_t4201FB60 = 
	{
		0x00
	};
word16 g_w4201FB98 = 0x00;
byte g_b4201FB9A = 0x00;
Eq_117003 g_t4201FBFC = 
	{
		0x00,
	};
word16 g_w4201FC02 = 0x00;
byte g_b4201FC04 = 0x00;
byte g_b4201FC08 = 0x00;
int32 g_dw4201FC0C = 0;
int32 g_dw4201FC10 = 0;
int32 g_dw4201FC14 = 0;
byte g_b4201FC5C = 0x00;
byte g_b4201FC5D = 0x00;
byte g_b4201FC5E = 0x00;
byte g_b4201FC5F = 0x00;
byte g_b4201FC60 = 0x00;
byte g_b4201FC61 = 0x00;
byte g_b4201FC62 = 0x00;
byte g_b4201FC63 = 0x00;
byte g_b4201FCDF = 0x00;
byte g_b4201FCE0 = 0x00;
byte g_b4201FD44 = 0x00;
byte g_b4201FD46 = 0x00;
byte g_b4201FD47 = 0x00;
byte g_b4201FD48 = 0x00;
byte g_b4201FD49 = 0x00;
byte g_b4201FD4B = 0x00;
byte g_b4201FD4C = 0x00;
byte g_b4201FD4D = 0x00;
Eq_2 g_t4201FD50 = 
	{
		0x00
	};
int32 g_dw4201FD58 = 0;
byte g_b4201FD5C = 0x00;
struct Eq_196893 * g_ptr4201FD64 = null;
struct Eq_196885 * g_ptr4201FD68 = null;
struct Eq_196910 * g_ptr4201FD6C = null;
Eq_2 g_t4201FD70 = 
	{
		0x00
	};
Eq_2 g_t4201FD74 = 
	{
		0x00
	};
Eq_196867 g_t4201FD80 = 
	{
		0x00,
	};
byte g_b4201FD81 = 0x00;
byte g_b4201FD82 = 0x00;
byte g_b4201FD83 = 0x00;
byte g_b4201FD84 = 0x00;
byte g_b4201FD85 = 0x00;
byte g_b4201FD86 = 0x00;
byte g_b4201FD87 = 0x00;
byte g_b4201FD88 = 0x00;
byte g_b4201FD89 = 0x00;
Eq_2 g_t4201FD8C = 
	{
		0x00
	};
Eq_2 g_t4201FD90 = 
	{
		0x00
	};
byte g_b4201FD94 = 0x00;
Eq_200212 g_t4201FD98 = 
	{
		0x00,
	};
uint16 g_w4201FDA2 = 0x00;
uint16 g_w4201FDB2 = 0x00;
uint16 g_w4201FDB6 = 0x00;
uint16 g_w4201FDBA = 0x00;
uint16 g_w4201FDBC = 0x00;
uint16 g_w4201FDC0 = 0x00;
uint16 g_w4201FDC6 = 0x00;
uint16 g_w4201FDC8 = 0x00;
uint16 g_w4201FDCA = 0x00;
uint16 g_w4201FDCE = 0x00;
uint16 g_w4201FDD6 = 0x00;
uint16 g_w4201FDDC = 0x00;
uint16 g_w4201FDE0 = 0x00;
uint16 g_w4201FDE2 = 0x00;
uint16 g_w4201FDE6 = 0x00;
uint16 g_w4201FDF0 = 0x00;
uint16 g_w4201FDFA = 0x00;
uint16 g_w4201FDFC = 0x00;
uint16 g_w4201FE04 = 0x00;
uint16 g_w4201FE06 = 0x00;
uint16 g_w4201FE08 = 0x00;
uint16 g_w4201FE0A = 0x00;
uint16 g_w4201FE0C = 0x00;
uint16 g_w4201FE0E = 0x00;
uint16 g_w4201FE10 = 0x00;
uint16 g_w4201FE14 = 0x00;
uint16 g_w4201FE16 = 0x00;
uint16 g_w4201FE1A = 0x00;
uint16 g_w4201FE1E = 0x00;
uint16 g_w4201FE22 = 0x00;
uint16 g_w4201FE2A = 0x00;
uint16 g_w4201FE2C = 0x00;
uint16 g_w4201FE2E = 0x00;
uint16 g_w4201FE32 = 0x00;
uint16 g_w4201FE34 = 0x00;
uint16 g_w4201FE36 = 0x00;
uint16 g_w4201FE38 = 0x00;
uint16 g_w4201FE3C = 0x00;
uint16 g_w4201FE40 = 0x00;
uint16 g_w4201FE42 = 0x00;
uint16 g_w4201FE44 = 0x00;
uint16 g_w4201FE48 = 0x00;
uint16 g_w4201FE4A = 0x00;
uint16 g_w4201FE4C = 0x00;
int32 g_a4201FE50[] = 
	{
	};
uint16 * g_ptr4201FE58 = null;
uint16 g_w4201FE8C = 0x00;
uint16 g_w4201FE90 = 0x00;
uint16 g_w4201FE92 = 0x00;
uint16 g_w4201FE94 = 0x00;
uint16 g_w4201FE96 = 0x00;
uint16 g_w4201FE98 = 0x00;
uint16 g_w4201FE9A = 0x00;
uint16 g_w4201FE9C = 0x00;
Eq_2 g_t4201FEA0 = 
	{
		0x00
	};
Eq_210739 g_t4201FEA4 = 
	{
		0x00
	};
Eq_2 g_t4201FEA8 = 
	{
		0x00
	};
Eq_2 g_t4201FEAC = 
	{
		0x00
	};
Eq_2 g_t4201FEB0 = 
	{
		0x00
	};
Eq_2 g_t4201FEB8 = 
	{
		0x00
	};
Eq_2 g_t4201FEBC = 
	{
		0x00
	};
Eq_2 g_t4201FEC0 = 
	{
		0x00
	};
struct Eq_197081 * g_ptr4201FEC4 = null;
Eq_2 g_t4201FEC8 = 
	{
		0x00
	};
Eq_2 g_t4201FED0 = 
	{
		0x00
	};
Eq_2 g_t4201FED4 = 
	{
		0x00
	};
Eq_2 g_t4201FED8 = 
	{
		0x00
	};
Eq_206686 g_t42020000 = 
	{
		0x00
	};
Eq_2 g_t4202000C = 
	{
		0x00
	};
struct Eq_206963 * g_ptr42020074 = null;
Eq_260061 g_t42020180 = 
	{
		0x00,
		0x00,
		0x00,
	};
Eq_363347 g_a420201D0[21] = 
	{
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
		},
	};
byte g_a42020224[21] = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_224949 g_t420207B7 = 
	{
		null,
	};
Eq_2 g_t420207FC = 
	{
		0x00
	};
Eq_260872 g_t42020814 = 
	{
		0x00,
	};
Eq_363343 g_a4202088C[11] = 
	{
		
		{
			0x00,
		},
		
		{
			0x00,
		},
		
		{
			0x00,
		},
		
		{
			0x00,
		},
		
		{
			0x00,
		},
		
		{
			0x00,
		},
		
		{
			0x00,
		},
		
		{
			0x00,
		},
		
		{
			0x00,
		},
		
		{
			0x00,
		},
		
		{
			?? /* Can't read address 42020DDC */
,
		},
	};
byte g_a42020BFC[] = 
	{
	};
byte g_b42020C7C = 0x00;
Eq_260051 g_t42020CEC = 
	{
		0x00,
	};
byte g_b42020D44 = 0x00;
Eq_2 g_t42020D50 = 
	{
		0x00
	};
int32 g_dw42020D54 = 0;
