// bl602_demo_wifi_init.c
// Generated by decompiling bl602_demo_wifi.elf
// using Reko decompiler version 0.9.3.0.

#include "bl602_demo_wifi.h"

// 23000000: void bl602_start(Register Eq_2 s1, Register Eq_2 s2, Register ptr32 fcsr, Register ptr32 mstatus, Register ptr32 misa, Register ptr32 mie, Register ptr32 mtvec)
void bl602_start(Eq_2 s1, Eq_2 s2, ptr32 fcsr, ptr32 mstatus, ptr32 misa, ptr32 mie, ptr32 mtvec)
{
	__csrrc(mstatus, 0x00);
	int32 * a0_10 = &g_b42049C00;
	word32 * a1_12 = &g_b4200D9C8;
	if (0x4200D9C8 < 0x4200DC20)
	{
		do
		{
			*a1_12 = *a0_10;
			++a0_10;
			++a1_12;
		} while (a1_12 < &g_dw4200DC20);
	}
	int32 * a0_23 = hal_boot2_get_flash_addr();
	word32 * a1_26 = &g_dw4200DC20;
	if (0x4200DC20 < 0x4200DC78)
	{
		do
		{
			*a1_26 = *a0_23;
			++a0_23;
			++a1_26;
		} while (a1_26 < &g_dw4200DC78);
	}
	int32 * a0_38 = (int32 *) 587785524;
	word32 * a1_40 = &g_dw4200C498;
	if (0x4200C498 < 0x4200D9C8)
	{
		do
		{
			*a1_40 = *a0_38;
			++a0_38;
			++a1_40;
		} while (a1_40 < &g_b4200D9C8);
	}
	word32 * a0_52 = &g_dw4200DC78;
	if (0x4200DC78 < 0x42020D66)
	{
		do
		{
			*a0_52 = 0x00;
			++a0_52;
		} while (a0_52 < (word32 *) 0x42020D66);
		word32 * a0_60 = &g_t42042000;
		if (0x42042000 < 0x4204B7A0)
		{
			do
			{
				*a0_60 = 0x00;
				++a0_60;
			} while (a0_60 < (word32 *) 0x4204B7A0);
		}
	}
	__csrrs(mstatus, 0x00);
	if ((__csrrs(mstatus, 0x00) & 0x06000000) != 0x00)
		__csrrw(fcsr, 0x4200C7F0);
	g_t42041FF4.u0 = 0x230000E8;
	bfl_main(0x230000E8, s1, s2, fcsr, mstatus, misa, mie, mtvec, g_t42041FF0, g_t42041FF4, g_t42041FF8, g_t42041FFC, g_t42042000, g_t42042004, g_t42042008, g_t42042010, g_t42042014, g_t42042018, g_t42042020, g_t42042024, g_t42042028, g_t4204202C, g_t42042034, g_t42042038, g_t4204203C, g_t42042044, g_t42042058, g_t4204205C, g_t4204206C, g_t42042078, g_t42042084, g_t42042088, g_t42042098, g_t420420A4, g_t420420A8, g_t420420B8, g_t420420C8, g_t420420D8, g_t420420E8, g_t420420F8, g_t42042108, g_t42042124, g_t42042128, g_t42042144, g_t42042164);
	while (true)
		;
}

