// bl602_demo_wifi_wifibss.c
// Generated by decompiling bl602_demo_wifi.elf
// using Reko decompiler version 0.9.3.0.

#include "bl602_demo_wifi.h"

Eq_2 g_t42042000 = 
	{
		0x00
	};
Eq_2 g_t42042004 = 
	{
		0x00
	};
Eq_2 g_t42042008 = 
	{
		0x00
	};
Eq_2 g_t42042010 = 
	{
		0x00
	};
Eq_2 g_t42042014 = 
	{
		0x00
	};
Eq_2 g_t42042018 = 
	{
		0x00
	};
Eq_2 g_t42042020 = 
	{
		0x00
	};
Eq_2 g_t42042024 = 
	{
		0x00
	};
Eq_2 g_t42042028 = 
	{
		0x00
	};
Eq_2 g_t4204202C = 
	{
		0x00
	};
Eq_2 g_t42042034 = 
	{
		0x00
	};
Eq_2 g_t42042038 = 
	{
		0x00
	};
Eq_2 g_t4204203C = 
	{
		0x00
	};
Eq_2 g_t42042044 = 
	{
		0x00
	};
Eq_2 g_t42042058 = 
	{
		0x00
	};
Eq_2 g_t4204205C = 
	{
		0x00
	};
Eq_2 g_t4204206C = 
	{
		0x00
	};
Eq_2 g_t42042078 = 
	{
		0x00
	};
Eq_2 g_t42042084 = 
	{
		0x00
	};
Eq_2 g_t42042088 = 
	{
		0x00
	};
Eq_2 g_t42042098 = 
	{
		0x00
	};
Eq_2 g_t420420A4 = 
	{
		0x00
	};
Eq_2 g_t420420A8 = 
	{
		0x00
	};
Eq_2 g_t420420B8 = 
	{
		0x00
	};
Eq_2 g_t420420C8 = 
	{
		0x00
	};
Eq_2 g_t420420D8 = 
	{
		0x00
	};
Eq_2 g_t420420E8 = 
	{
		0x00
	};
Eq_2 g_t420420F8 = 
	{
		0x00
	};
Eq_2 g_t42042108 = 
	{
		0x00
	};
Eq_2 g_t42042124 = 
	{
		0x00
	};
Eq_2 g_t42042128 = 
	{
		0x00
	};
Eq_2 g_t42042144 = 
	{
		0x00
	};
Eq_2 g_t42042164 = 
	{
		0x00
	};
word32 g_dw42042220 = 0x00;
word32 g_dw42043004 = 0x00;
word32 g_dw42043088 = 0x00;
word32 g_dw4204310C = 0x00;
word32 g_dw42043190 = 0x00;
Eq_362946 g_a42043608[] = 
	{
	};
word32 g_dw42046120 = 0x00;
Eq_362949 g_a42046124[14] = 
	{
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
		
		{
			
			{
				0x00
			},
			0x00,
			0x00,
			0,
		},
	};
Eq_363093 g_a420463C4[3] = 
	{
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
	};
Eq_363079 g_a4204643C[11] = 
	{
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
	};
Eq_362961 g_a42046694[] = 
	{
	};
word32 g_dw420470B4 = 0x00;
word32 g_dw420470C0 = 0x00;
word32 g_dw420470C4 = 0x00;
word32 g_dw420470CC = 0x00;
word32 g_dw420470D0 = 0x00;
word32 g_dw420470D4 = 0x00;
word32 g_dw420470DC = 0x00;
word32 g_dw420470E0 = 0x00;
word32 g_dw420470E4 = 0x00;
word32 g_dw420470E8 = 0x00;
word32 g_dw420470EC = 0x00;
struct Eq_12399 g_t42047264 = 
	{
		
		{
			?? /* Can't read address 84061F86 */

		},
		?? /* Can't read address 84061F88 */
,
		
		{
			?? /* Can't read address 84061F90 */

		},
		?? /* Can't read address 84061F91 */
,
		?? /* Can't read address 84061F92 */
,
		?? /* Can't read address 8408ED34 */
,
		,
	};
Eq_363101 g_a420473AC[3] = 
	{
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
	};
Eq_363087 g_a42047424[11] = 
	{
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
	};
word32 g_dw42047A2C = 0x00;
word32 g_dw42047A38 = 0x00;
word32 g_dw42047A3C = 0x00;
struct Eq_22136 * g_ptr42047A40 = null;
word32 g_dw42047A44 = 0x00;
word32 g_dw42047A48 = 0x00;
word32 g_dw42047A4C = 0x00;
word32 g_dw42047A54 = 0x00;
word32 g_dw42047A58 = 0x00;
word32 g_dw42047A5C = 0x00;
word32 g_dw42047A60 = 0x00;
word32 g_dw42047A64 = 0x00;
ptr32 g_a42047A80[] = 
	{
	};
struct Eq_12667 g_t42047AB8 = 
	{
		
		{
			?? /* Can't read address 840627DA */

		},
		?? /* Can't read address 840627DC */
,
		
		{
			?? /* Can't read address 840627E4 */

		},
		?? /* Can't read address 840627E5 */
,
		?? /* Can't read address 840627E6 */
,
		?? /* Can't read address 8408F588 */
,
		,
	};
struct Eq_13594 * g_a42047AC8[] = 
	{
	};
Eq_22130 g_t42047AE0 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_362956 g_a42047AE4[] = 
	{
	};
Eq_362962 g_a42047B4C[] = 
	{
	};
Eq_362963 g_a42047C14[5] = 
	{
		
		{
			null,
		},
		
		{
			null,
		},
		
		{
			null,
		},
		
		{
			null,
		},
		
		{
			null,
		},
	};
ptr32 g_ptr42047CE4 = 0x00;
word32 g_dw42047CF4 = 0x00;
word32 g_dw42047D00 = 0x00;
byte g_b42047D05 = 0x00;
byte g_a42047D06[9] = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
word32 g_dw42047D08 = 0x00;
Eq_36302 g_t42047D0E = 
	{
		
		{
			0x00
		},
		0x00,
		0x00,
	};
word32 g_dw42047D1C = 0x00;
Eq_36323 g_t42047DCC = 
	{
		0x00,
	};
Eq_34220 g_t42047DD4 = 
	{
		0x00
	};
byte g_a42047DDC[] = 
	{
	};
byte g_b42047DDD = 0x00;
word32 g_dw42047DE0 = 0x00;
byte g_b42047F70 = 0x00;
int8 g_b42047FB0 = 0;
int32 g_dw42047FB8 = 0;
int32 g_dw42047FBC = 0;
byte g_b42047FC4 = 0x00;
byte g_b42048D04 = 0x00;
byte g_a42048D0E[] = 
	{
	};
byte g_b42048FB0 = 0x00;
word32 g_dw42048FB4 = 0x00;
word32 g_dw42048FB8 = 0x00;
word32 g_dw42048FBC = 0x00;
byte g_b42049C00 = 0x00;
