#ifndef __UTILS_TLV_BL_H__
#define __UTILS_TLV_BL_H__

enum CFG_ELEMENT_TYPE {
	CFG_ELEMENT_TYPE_UNKNOWN = 0,
	CFG_ELEMENT_TYPE_BOOLEAN = 1,
	CFG_ELEMENT_TYPE_SINT8 = 2,
	CFG_ELEMENT_TYPE_UINT8 = 3,
	CFG_ELEMENT_TYPE_SINT16 = 4,
	CFG_ELEMENT_TYPE_UINT16 = 5,
	CFG_ELEMENT_TYPE_SINT32 = 6,
	CFG_ELEMENT_TYPE_UINT32 = 7,
	CFG_ELEMENT_TYPE_STRING = 8
};

enum CFG_ELEMENT_TYPE_OPS {
	CFG_ELEMENT_TYPE_OPS_SET = 0,
	CFG_ELEMENT_TYPE_OPS_GET = 1,
	CFG_ELEMENT_TYPE_OPS_RESET = 2,
	CFG_ELEMENT_TYPE_OPS_DUMP_DEBUG = 3,
	CFG_ELEMENT_TYPE_OPS_UNKNOWN = 4
};

void utils_tlv_bl_unpack_auto(void);

#endif // __UTILS_TLV_BL_H__
