
BL_Err_Type UART_AutoBaudDetection(UART_ID_Type uartId, BL_Fun_Type autoBaud);
BL_Err_Type UART_ClrRtsValue(UART_ID_Type uartId);
BL_Err_Type UART_DeInit(UART_ID_Type uartId);
BL_Err_Type UART_Disable(UART_ID_Type uartId, UART_Direction_Type direct);
BL_Err_Type UART_Enable(UART_ID_Type uartId, UART_Direction_Type direct);
BL_Err_Type UART_FifoConfig(UART_ID_Type uartId, UART_FifoCfg_Type * fifoCfg);
uint16_t UART_GetAutoBaudCount(UART_ID_Type uartId, UART_AutoBaudDetection_Type autoBaudDet);
BL_Sts_Type UART_GetIntStatus(UART_ID_Type uartId, UART_INT_Type intType);
BL_Sts_Type UART_GetOverflowStatus(UART_ID_Type uartId, UART_Overflow_Type overflow);
BL_Sts_Type UART_GetRxBusBusyStatus(UART_ID_Type uartId);
uint8_t UART_GetRxFifoCount(UART_ID_Type uartId);
BL_Sts_Type UART_GetTxBusBusyStatus(UART_ID_Type uartId);
uint8_t UART_GetTxFifoCount(UART_ID_Type uartId);
BL_Err_Type UART_Init(UART_ID_Type uartId, UART_CFG_Type * uartCfg);
BL_Err_Type UART_Int_Callback_Install(UART_ID_Type uartId, UART_INT_Type intType, intCallback_Type * cbFun);
BL_Err_Type UART_IntClear(UART_ID_Type uartId, UART_INT_Type intType);
BL_Err_Type UART_IntMask(UART_ID_Type uartId, UART_INT_Type intType, BL_Mask_Type intMask);
BL_Err_Type UART_IrConfig(UART_ID_Type uartId, UART_IrCfg_Type * irCfg);
uint32_t UART_ReceiveData(UART_ID_Type uartId, uint8_t * data, uint32_t maxLen);
BL_Err_Type UART_RxFifoClear(UART_ID_Type uartId);
BL_Err_Type UART_SendData(UART_ID_Type uartId, uint8_t * data, uint32_t len);
BL_Err_Type UART_SendDataBlock(UART_ID_Type uartId, uint8_t * data, uint32_t len);
BL_Err_Type UART_SetBaudrate(UART_ID_Type uartId, UART_AutoBaudDetection_Type autoBaudDet);
BL_Err_Type UART_SetDeglitchCount(UART_ID_Type uartId, uint8_t deglitchCnt);
BL_Err_Type UART_SetRtsValue(UART_ID_Type uartId);
BL_Err_Type UART_SetRxDataLength(UART_ID_Type uartId, uint16_t length);
BL_Err_Type UART_SetRxTimeoutValue(UART_ID_Type uartId, uint8_t time);
BL_Err_Type UART_SetTxDataLength(UART_ID_Type uartId, uint16_t length);
BL_Err_Type UART_TxFifoClear(UART_ID_Type uartId);
BL_Err_Type UART_TxFreeRun(UART_ID_Type uartId, BL_Fun_Type txFreeRun);
