
BL_Err_Type HBN_32K_Sel(HBN_32K_CLK_Type clkType);
BL_Err_Type HBN_Aon_Pad_IeSmt_Cfg(uint8_t padCfg);
BL_Err_Type HBN_App_Reset(uint8_t npXtalType, uint8_t bclkDiv, uint8_t apXtalType, uint8_t fclkDiv);
BL_Err_Type HBN_Clear_IRQ(HBN_INT_Type irqType);
BL_Err_Type HBN_Clear_RTC_Counter(void);
BL_Err_Type HBN_Clear_RTC_INT(void);
BL_Err_Type HBN_Disable(void);
BL_Err_Type HBN_Disable_AComp0_IRQ(void);
BL_Err_Type HBN_Disable_AComp1_IRQ(void);
BL_Err_Type HBN_Disable_BOR_IRQ(void);
void HBN_Enable(uint8_t aGPIOIeCfg, HBN_LDO_LEVEL_Type ldoLevel, HBN_LEVEL_Type hbnLevel);
BL_Err_Type HBN_Enable_AComp0_IRQ(void);
BL_Err_Type HBN_Enable_AComp1_IRQ(void);
BL_Err_Type HBN_Enable_BOR_IRQ(void);
BL_Err_Type HBN_Enable_RTC_Counter(void);
BL_Sts_Type HBN_Get_BOR_OUT_State(void);
BL_Sts_Type HBN_Get_INT_State(HBN_INT_Type irqType);
uint8_t HBN_Get_Pin_Wakeup_Mode(void);
uint16_t HBN_Get_PIR_Interval(void);
uint16_t HBN_Get_PIR_Threshold(void);
BL_Err_Type HBN_Get_RTC_Timer_Val(uint32_t * valLow, uint32_t * valHigh);
uint32_t HBN_Get_Status_Flag(void);
uint32_t HBN_Get_Wakeup_Addr(void);
BL_Err_Type HBN_GPIO7_Dbg_Pull_Cfg(BL_Fun_Type pupdEn, BL_Fun_Type iesmtEn, BL_Fun_Type dlyEn, uint8_t dlySec);
BL_Err_Type HBN_GPIO_INT_Disable(void);
BL_Err_Type HBN_GPIO_INT_Enable(HBN_GPIO_INT_Trigger_Type gpioIntTrigType);
BL_Err_Type HBN_Hw_Pu_Pd_Cfg(uint8_t enable);
void HBN_Mode_Enter(HBN_APP_CFG_Type * cfg);
BL_Err_Type HBN_Out0_Callback_Install(HBN_OUT0_INT_Type intType, intCallback_Type * cbFun);
BL_Err_Type HBN_Out1_Callback_Install(HBN_OUT1_INT_Type intType, intCallback_Type * cbFun);
BL_Err_Type HBN_Pin_WakeUp_Mask(uint8_t maskVal);
BL_Err_Type HBN_PIR_Disable(void);
BL_Err_Type HBN_PIR_Enable(void);
BL_Err_Type HBN_PIR_HPF_Sel(HBN_PIR_HPF_Type hpf);
BL_Err_Type HBN_PIR_INT_Config(HBN_PIR_INT_CFG_Type * pirIntCfg);
BL_Err_Type HBN_PIR_LPF_Sel(HBN_PIR_LPF_Type lpf);
void HBN_Power_Down_Flash(SPI_Flash_Cfg_Type * flashCfg);
BL_Err_Type HBN_Power_Off_RC32K(void);
BL_Err_Type HBN_Power_Off_Xtal_32K(void);
BL_Err_Type HBN_Power_On_RC32K(void);
BL_Err_Type HBN_Power_On_Xtal_32K(void);
BL_Err_Type HBN_Reset(void);
BL_Err_Type HBN_Set_BOR_Cfg(HBN_BOR_CFG_Type * cfg);
BL_Err_Type HBN_Set_BOR_Config(uint8_t enable, HBN_BOR_THRES_Type threshold, HBN_BOR_MODE_Type mode);
BL_Err_Type HBN_Set_Embedded_Flash_Pullup(uint8_t enable);
BL_Err_Type HBN_Set_HRAM_Ret(void);
BL_Err_Type HBN_Set_HRAM_slp(void);
BL_Err_Type HBN_Set_Ldo11_All_Vout(HBN_LDO_LEVEL_Type ldoLevel);
BL_Err_Type HBN_Set_Ldo11_Aon_Vout(HBN_LDO_LEVEL_Type ldoLevel);
BL_Err_Type HBN_Set_Ldo11_Rt_Vout(HBN_LDO_LEVEL_Type ldoLevel);
BL_Err_Type HBN_Set_Ldo11_Soc_Vout(HBN_LDO_LEVEL_Type ldoLevel);
BL_Err_Type HBN_Set_PIR_Interval(uint16_t interval);
BL_Err_Type HBN_Set_PIR_Threshold(uint16_t threshold);
BL_Err_Type HBN_Set_ROOT_CLK_Sel(HBN_ROOT_CLK_Type rootClk);
BL_Err_Type HBN_Set_RTC_Timer(HBN_RTC_INT_Delay_Type delay, uint32_t compValLow, uint32_t compValHigh, uint8_t compMode);
BL_Err_Type HBN_Set_Status_Flag(uint32_t flag);
BL_Err_Type HBN_Set_UART_CLK_Sel(HBN_UART_CLK_Type clkSel);
BL_Err_Type HBN_Set_Wakeup_Addr(uint32_t addr);
BL_Err_Type HBN_Set_XCLK_CLK_Sel(HBN_XCLK_CLK_Type xClk);
BL_Err_Type HBN_Trim_RC32K(void);
