
void ps_polling_frame(vif_info_tag * );
int bl60x_edca_get(int ac, uint8_t * aifs, uint8_t * cwmin, uint8_t * cwmax, uint16_t * txop);
int mm_add_if_req_handler(ke_msg_id_t msgid, mm_add_if_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_ba_add_req_handler(ke_msg_id_t msgid, mm_ba_add_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_bcn_change_req_handler(ke_msg_id_t msgid, mm_bcn_change_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_cfg_rssi_req_handler(ke_msg_id_t msgid, mm_cfg_rssi_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_chan_ctxt_update_req_handler(ke_msg_id_t msgid, mm_chan_ctxt_update_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_force_idle_req_handler(ke_msg_id_t msgid, mm_force_idle_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_hw_config_handler(ke_msg_id_t msgid, void * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_key_add_req_handler(ke_msg_id_t msgid, mm_key_add_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_key_del_req_handler(ke_msg_id_t msgid, mm_key_del_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_monitor_channel_req_handler(ke_msg_id_t msgid, mm_monitor_channel_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_monitor_enable_req_handler(ke_msg_id_t msgid, mm_monitor_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_remain_on_channel_req_handler(ke_msg_id_t msgid, mm_remain_on_channel_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_remove_if_req_handler(ke_msg_id_t msgid, mm_remove_if_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_reset_req_handler(ke_msg_id_t msgid, void * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_basic_rates_req_handler(ke_msg_id_t msgid, mm_set_basic_rates_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_beacon_int_req_handler(ke_msg_id_t msgid, mm_set_beacon_int_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_bssid_req_handler(ke_msg_id_t msgid, mm_set_bssid_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_channel_req_handler(ke_msg_id_t msgid, mm_set_channel_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_dtim_req_handler(ke_msg_id_t msgid, mm_set_dtim_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_edca_req_handler(ke_msg_id_t msgid, mm_set_edca_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_filter_req_handler(ke_msg_id_t msgid, mm_set_filter_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_idle_req_handler(ke_msg_id_t msgid, mm_set_idle_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_mode_req_handler(ke_msg_id_t msgid, mm_set_mode_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_power_req_handler(ke_msg_id_t msgid, mm_set_power_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_ps_mode_req_handler(ke_msg_id_t msgid, mm_set_ps_mode_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_ps_options_req_handler(ke_msg_id_t msgid, mm_set_ps_options_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_slottime_req_handler(ke_msg_id_t msgid, mm_set_slottime_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_set_vif_state_req_handler(ke_msg_id_t msgid, mm_set_vif_state_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_sta_add_req_handler(ke_msg_id_t msgid, mm_sta_add_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_sta_del_req_handler(ke_msg_id_t msgid, mm_sta_del_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_start_req_handler(ke_msg_id_t msgid, mm_start_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_tim_update_req_handler(ke_msg_id_t msgid, mm_tim_update_req * param, ke_task_id_t dest_id, ke_task_id_t src_id);
int mm_version_req_handler(ke_msg_id_t msgid, void * param, ke_task_id_t dest_id, ke_task_id_t src_id);
void ps_polling_frame(void);
