// sdk_app_ble_sync_rodata_0001.c
// Generated by decompiling sdk_app_ble_sync.elf
// using Reko decompiler version 0.9.3.0.

#include "sdk_app_ble_sync.h"

Eq_375 g_t2307E750 = 
	{
		0x5B,
		
		{
			101
		},
	};
Eq_375 g_t2307E928 = 
	{
		0x77,
		
		{
			118
		},
	};
Eq_375 g_t2307E93C = 
	{
		0x25,
		
		{
			76
		},
	};
Eq_375 g_t2307E940 = 
	{
		0x70,
		
		{
			114
		},
	};
Eq_375 g_t2307EAB4 = 
	{
		0x25,
		
		{
			52
		},
	};
Eq_375 g_t2307EB3C = 
	{
		0x2D,
		
		{
			0
		},
	};
Eq_375 g_t2307EBB4 = 
	{
		0x2D,
		
		{
			0x0078
		},
	};
Eq_375 g_t2307EC2C = 
	{
		0x55,
		
		{
			65
		},
	};
<anonymous> * g_a2307ED8C[] = 
	{
	};
Eq_375 g_t2307F0F4 = 
	{
		115,
		
		{
			91
		},
	};
Eq_375 g_t2307F168 = 
	{
		0x5B,
		
		{
			32
		},
	};
Eq_375 g_t2307F3BC = 
	{
		99,
		
		{
			78
		},
	};
Eq_375 g_t2307F4FC = 
	{
		0x5B,
		
		{
			-78
		},
	};
Eq_375 g_t2307F514 = 
	{
		0x25,
		
		{
			-112
		},
	};
Eq_375 g_t2307F51C = 
	{
		0x25,
		
		{
			-0x0044
		},
	};
Eq_375 g_t2307F540 = 
	{
		0x5B,
		
		{
			24
		},
	};
Eq_375 g_t2307F564 = 
	{
		0x5B,
		
		{
			-19
		},
	};
Eq_375 g_t2307F664 = 
	{
		117,
		
		{
			93
		},
	};
<anonymous> g_t2307F73C = <code>;
word32 g_dw2307F75C = 587615262;
Eq_375 g_t2307F7D0 = 
	{
		0x20,
		
		{
			-23
		},
	};
word32 g_a2307F81C[] = 
	{
	};
byte g_a2307FC74[] = 
	{
	};
word32 g_a2307FCD0[] = 
	{
	};
int32 g_a230800D0[] = 
	{
	};
word32 g_a230804D0[] = 
	{
	};
int32 g_a230808D0[] = 
	{
	};
int32 g_a23080DD0[] = 
	{
	};
word32 g_a230811D0[] = 
	{
	};
int32 g_a230815D0[] = 
	{
	};
struct Eq_355348 * g_a230819D0[] = 
	{
	};
<anonymous> g_t23081F3C = <code>;
Eq_375 g_t23081F8C = 
	{
		0x5B,
		
		{
			32
		},
	};
Eq_375 g_t23081FC0 = 
	{
		0x5B,
		
		{
			115
		},
	};
Eq_375 g_t2308202C = 
	{
		0x20,
		
		{
			0x0068
		},
	};
Eq_375 g_t2308203C = 
	{
		0x20,
		
		{
			76
		},
	};
Eq_375 g_t2308204C = 
	{
		0x20,
		
		{
			100
		},
	};
Eq_375 g_t23082064 = 
	{
		0x20,
		
		{
			36
		},
	};
Eq_375 g_t23082080 = 
	{
		0x20,
		
		{
			60
		},
	};
Eq_375 g_t230820C8 = 
	{
		0x5B,
		
		{
			6
		},
	};
Eq_375 g_t2308210C = 
	{
		0x3D,
		
		{
			7
		},
	};
Eq_375 g_t2308218C = 
	{
		0x20,
		
		{
			8
		},
	};
Eq_375 g_t230821A0 = 
	{
		0x20,
		
		{
			8
		},
	};
Eq_375 g_t23082218 = 
	{
		0x20,
		
		{
			2
		},
	};
Eq_375 g_t230822E4 = 
	{
		0x5B,
		
		{
			2
		},
	};
Eq_375 g_t23082338 = 
	{
		0x5B,
		
		{
			0x007C
		},
	};
Eq_375 g_t230823BC = 
	{
		0x5B,
		
		{
			0
		},
	};
Eq_375 g_t230823F8 = 
	{
		0x5B,
		
		{
			0
		},
	};
int32 g_a23082438[] = 
	{
	};
int32 g_a23082474[] = 
	{
	};
Eq_361233 g_t230824B0 = 
	{
		
		{
		},
	};
byte g_a230826D4[9] = 
	{
		0x00,
		0x60,
		0x04,
		0x00,
		~0x07,
		0x07,
		0x40,
		0x02,
		0x00,
	};
byte g_b230826DC = 0x00;
byte g_b230826DD = 0x03;
byte g_b230826DE = 0x01;
byte g_b230826DF = 0x02;
byte g_b230826E0 = 0x03;
Eq_73457 g_t230826FC = 
	{
		~0x00,
		~0x00,
	};
word32 g_dw2308277C = 0x2302E222;
struct Eq_182195 * g_ptr23082788 = &g_t0044;
struct Eq_207409 * g_a23082798[] = 
	{
	};
byte g_a230827A8[5] = 
	{
		0x01,
		0x03,
		0x1C,
		0x06,
		0x00,
	};
union Eq_16005 * g_ptr230827AC = null;
int32 g_dw230827B0 = -1;
struct Eq_207642 * g_a230827CC[] = 
	{
	};
byte g_a230827EC[] = 
	{
	};
byte g_b230827F8 = 0x00;
byte g_b230827F9 = 0x0F;
byte g_b230827FA = 0xAC;
Eq_303292 g_t2308289C = 
	{
		
		{
		},
		1601463667,
	};
Eq_2 g_t230828BC = 
	{
		-28
	};
Eq_186511 g_t23082C38 = 
	{
		
		{
			24
		},
		help_cmd,
	};
