// sdk_app_ble_sync_init.c
// Generated by decompiling sdk_app_ble_sync.elf
// using Reko decompiler version 0.9.3.0.

#include "sdk_app_ble_sync.h"

// 23000000: void bl602_start(Register Eq_2 s0, Register Eq_2 s2, Register Eq_2 s3, Register ptr32 fcsr, Register ptr32 mstatus, Register ptr32 misa, Register ptr32 mie, Register ptr32 mtvec)
void bl602_start(Eq_2 s0, Eq_2 s2, Eq_2 s3, ptr32 fcsr, ptr32 mstatus, ptr32 misa, ptr32 mie, ptr32 mtvec)
{
	__csrrc(mstatus, 0x00);
	int32 * a0_10 = (int32 *) 0x42049C00;
	word32 * a1_12 = &g_dw4200DDD4;
	if (0x4200DDD4 < 0x4200E02C)
	{
		do
		{
			*a1_12 = *a0_10;
			++a0_10;
			++a1_12;
		} while (a1_12 < &g_dw4200E02C);
	}
	struct Eq_23 * a5_24;
	int32 * a0_23 = hal_boot2_get_flash_addr(out a5_24);
	word32 * a1_26 = &g_dw4200E02C;
	if (0x4200E02C < 0x4200E084)
	{
		do
		{
			*a1_26 = *a0_23;
			++a0_23;
			++a1_26;
		} while (a1_26 < (word32 *) 0x4200E084);
	}
	int32 * a0_38 = (int32 *) 587738668;
	word32 * a1_40 = &g_dw4200C498;
	if (0x4200C498 < 0x4200DDD4)
	{
		do
		{
			*a1_40 = *a0_38;
			++a0_38;
			++a1_40;
		} while (a1_40 < &g_dw4200DDD4);
	}
	word32 * a0_52 = &g_b4200E088;
	if (0x4200E088 < 0x4201EEFF)
	{
		do
		{
			*a0_52 = 0x00;
			++a0_52;
		} while (a0_52 < (word32 *) 0x4201EEFF);
		word32 * a0_60 = &g_t42040000;
		if (0x42040000 < 0x420497A0)
		{
			do
			{
				*a0_60 = 0x00;
				++a0_60;
			} while (a0_60 < (word32 *) 0x420497A0);
		}
	}
	__csrrs(mstatus, 0x00);
	if ((__csrrs(mstatus, 0x00) & 0x06000000) != 0x00)
		__csrrw(fcsr, 0x4200C7F0);
	g_t4203FFF4.u0 = 0x230000E8;
	bfl_main(0x06000000, s0, a5_24, s2, s3, fcsr, mstatus, misa, mie, mtvec, g_t4203FFF0, g_t4203FFF4, g_t4203FFF8, g_t42040000, g_t42040004, g_t42040008, g_t42040010, g_t42040014, g_t42040018, g_t4204001C, g_t42040024, g_t42040028, g_t4204002C, g_t42040034, g_t42040038, g_t42040048, g_t4204004C, g_t4204005C, g_t42040068, g_t42040074, g_t42040078, g_t42040088, g_t42040094, g_t42040098, g_t420400A8, g_t420400B8, g_t420400C8, g_t420400D8, g_t420400E8, g_t420400F8, g_t42040114, g_t42040118, g_t42040134, g_t42040154);
	while (true)
		;
}

