// sdk_app_ble_sync_boot2.c
// Generated by decompiling sdk_app_ble_sync.elf
// using Reko decompiler version 0.9.3.0.

#include "sdk_app_ble_sync.h"

word32 g_dw4200DDD4 = 0x00;
int32 g_dw4200DDD8 = 0;
uint16 g_w4200DDDE = 0x00;
Eq_1104 g_a4200DDE4[] = 
	{
	};
Eq_104052 g_t4200E000 = 
	{
		0x00
	};
int32 * g_ptr4200E004 = null;
word32 g_dw4200E02C = 0x00;
byte g_b4200E03D = 0x00;
Eq_202961 g_t4200E044 = 
	{
		0x00
	};
