// sdk_app_ble_sync_stack.c
// Generated by decompiling sdk_app_ble_sync.elf
// using Reko decompiler version 0.9.3.0.

#include "sdk_app_ble_sync.h"

Eq_2 g_t4203FFF0 = 
	{
		0
	};
Eq_2 g_t4203FFF4 = 
	{
		0
	};
Eq_2 g_t4203FFF8 = 
	{
		0
	};
