// sdk_app_ble_sync_bss_0001.c
// Generated by decompiling sdk_app_ble_sync.elf
// using Reko decompiler version 0.9.3.0.

#include "sdk_app_ble_sync.h"

int32 g_dw4201E20C = 0;
Eq_333125 g_t4201E210 = 
	{
		
		{
			0
		},
	};
uint16 g_w4201E234 = 0x00;
uint16 g_w4201E236 = 0x00;
uint16 g_w4201E238 = 0x00;
byte g_b4201E23A = 0x00;
byte g_b4201E23B = 0x00;
int8 g_b4201E23C = 0;
int8 g_b4201E23D = 0;
byte g_b4201E23E = 0x00;
word16 g_w4201E240 = 0x00;
Eq_314166 g_t4201E242 = 
	{
		0x00
	};
Eq_326972 g_t4201E244 = 
	{
		0x00,
	};
uint16 g_w4201E256 = 0x00;
byte g_b4201E25A = 0x00;
uint16 g_w4201E272 = 0x00;
byte g_b4201E276 = 0x00;
uint16 g_w4201E28E = 0x00;
byte g_b4201E292 = 0x00;
Eq_325953 g_t4201E298 = 
	{
		
		{
			0
		},
	};
byte g_b4201E29C = 0x00;
byte g_b4201E29D = 0x00;
word16 g_w4201E29E = 0x00;
word16 g_w4201E2A0 = 0x00;
word16 g_w4201E2A2 = 0x00;
byte g_b4201E2A4 = 0x00;
word16 g_w4201E2A6 = 0x00;
word16 g_w4201E2AA = 0x00;
word16 g_w4201E2AE = 0x00;
byte g_b4201E2AF = 0x00;
byte g_b4201E2B1 = 0x00;
Eq_325953 g_t4201E2B4 = 
	{
		
		{
			0
		},
	};
byte g_b4201E2B8 = 0x00;
byte g_b4201E2B9 = 0x00;
word16 g_w4201E2BA = 0x00;
word16 g_w4201E2BC = 0x00;
word16 g_w4201E2BE = 0x00;
byte g_b4201E2C0 = 0x00;
word16 g_w4201E2C2 = 0x00;
word16 g_w4201E2C6 = 0x00;
byte g_b4201E2CA = 0x00;
byte g_b4201E2CB = 0x00;
byte g_b4201E2CD = 0x00;
Eq_325606 g_t4201E2D0 = 
	{
		
		{
			0
		},
	};
Eq_2 g_t4201E2E0 = 
	{
		0
	};
Eq_2 g_t4201E2F0 = 
	{
		0
	};
Eq_2 g_t4201E2F4 = 
	{
		0
	};
word32 g_dw4201E310 = 0x00;
Eq_2 g_t4201E320 = 
	{
		0
	};
int32 g_dw4201E338 = 0;
Eq_2 g_t4201E33C = 
	{
		0
	};
byte g_b4201E340 = 0x00;
byte g_b4201E341 = 0x00;
byte g_b4201E342 = 0x00;
byte g_b4201E343 = 0x00;
Eq_268388 g_t4201E344 = 
	{
		0x00,
		0x00,
	};
Eq_268388 g_t4201E34C = 
	{
		0x00,
		0x00,
	};
word16 g_w4201E35C = 0x00;
word16 g_w4201E35E = 0x00;
word32 g_dw4201E360 = 0x00;
int32 g_dw4201E364 = 0;
word16 g_w4201E368 = 0x00;
word16 g_w4201E36A = 0x00;
word16 g_w4201E36C = 0x00;
word16 g_w4201E36E = 0x00;
word16 g_w4201E370 = 0x00;
Eq_267340 g_t4201E372 = 
	{
		0x00
	};
byte g_b4201E373 = 0x00;
word16 g_w4201E380 = 0x00;
Eq_266640 g_t4201E382 = 
	{
		0x00
	};
byte g_b4201E383 = 0x00;
Eq_333101 g_t4201E38C = 
	{
		0,
	};
Eq_2 g_t4201E390 = 
	{
		0
	};
byte g_b4201E394 = 0x00;
byte g_b4201E395 = 0x00;
byte g_b4201E396 = 0x00;
Eq_268388 g_t4201E3A8 = 
	{
		0x00,
		0x00,
	};
word32 g_dw4201E3B4 = 0x00;
word32 g_dw4201E448 = 0x00;
word32 g_dw4201E468 = 0x00;
word32 g_dw4201E488 = 0x00;
word32 g_dw4201E4A8 = 0x00;
word32 g_dw4201E4C8 = 0x00;
word32 g_dw4201E4E8 = 0x00;
word32 g_dw4201E508 = 0x00;
word32 g_dw4201E528 = 0x00;
word32 g_dw4201E548 = 0x00;
Eq_334282 g_t4201E564 = 
	{
		0x00,
		0x00,
	};
word16 g_w4201E57C = 0x00;
byte g_b4201E57E = 0x00;
byte g_b4201E57F = 0x00;
Eq_274947 g_t4201E584 = 
	{
		0,
		0x00,
	};
Eq_335258 g_t4201E638 = 
	{
		0
	};
Eq_335261 g_t4201E63C = 
	{
		0
	};
Eq_268388 g_t4201E660 = 
	{
		0x00,
		0x00,
	};
Eq_268388 g_t4201E668 = 
	{
		0x00,
		0x00,
	};
Eq_268388 g_t4201E670 = 
	{
		0x00,
		0x00,
	};
Eq_268388 g_t4201E678 = 
	{
		0x00,
		0x00,
	};
Eq_268388 g_t4201E680 = 
	{
		0x00,
		0x00,
	};
struct Eq_270754 g_t4201E688 = 
	{
		null,
		null,
		null,
		null,
	};
byte g_b4201E694 = 0x00;
Eq_41391 g_t4201EED4 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
	};
struct Eq_297678 * g_ptr4201EED8 = null;
struct Eq_270707 * g_ptr4201EEDC = null;
int32 g_dw4201EEE0 = 0;
word32 g_dw4201EEE4 = 0x00;
word32 g_dw4201EEE8 = 0x00;
word32 g_dw4201EEEC = 0x00;
struct Eq_296472 * g_ptr4201EEF0 = null;
word32 g_dw4201EEF4 = 0x00;
Eq_2 g_t4201EEF8 = 
	{
		0
	};
byte g_b4201EEFE = 0x00;
