// sdk_app_ble_sync_bss_0000.c
// Generated by decompiling sdk_app_ble_sync.elf
// using Reko decompiler version 0.9.3.0.

#include "sdk_app_ble_sync.h"

byte g_b4200E088 = 0x00;
byte g_b4200E094 = 0x00;
byte g_b4200E095 = 0x00;
Eq_2 g_t4200E098 = 
	{
		0
	};
Eq_2 g_t4200E09C = 
	{
		0
	};
int32 g_dw4200E0A4 = 0;
word32 g_dw4200E0AC = 0x00;
<anonymous> * g_ptr4200E0BC = null;
word32 g_dw4200E0C0 = 0x00;
int32 g_dw4200E0C4 = 0;
Eq_33523 g_t4200E0C8 = 
	{
		0
	};
int32 g_dw4200E0CC = 0;
word32 g_dw4200E0D0 = 0x00;
<anonymous> * g_ptr4200E0D4 = null;
word32 g_dw4200E0D8 = 0x00;
<anonymous> * g_ptr4200E0DC = null;
word32 g_dw4200E0E0 = 0x00;
<anonymous> * g_ptr4200E0E4 = null;
<anonymous> * g_ptr4200E0E8 = null;
word32 g_dw4200E0EC = 0x00;
<anonymous> * g_ptr4200E0F0 = null;
word32 g_dw4200E0F4 = 0x00;
word32 g_dw4200E0F8 = 0x00;
word32 g_dw4200E0FC = 0x00;
Eq_2 g_t4200E100 = 
	{
		0
	};
int32 g_dw4200E104 = 0;
int32 g_dw4200E108 = 0;
int32 g_dw4200E10C = 0;
Eq_2 g_t4200E110 = 
	{
		0
	};
Eq_2 g_t4200E114 = 
	{
		0
	};
int32 g_dw4200E118 = 0;
struct Eq_38861 * g_ptr4200E11C = null;
byte g_b4200E129 = 0x00;
byte g_b4200E12A = 0x00;
<anonymous> * g_ptr4200E134 = null;
<anonymous> * g_ptr4200E138 = null;
<anonymous> * g_ptr4200E13C = null;
<anonymous> * g_ptr4200E140 = null;
<anonymous> * g_ptr4200E144 = null;
byte g_b4200E14C = 0x00;
int8 g_b4200E156 = 0;
uint16 g_w4200E158 = 0x00;
uint16 g_w4200E15A = 0x00;
<anonymous> * g_ptr4200E15C = null;
int32 g_dw4200E164 = 0;
byte g_b4200E168 = 0x00;
Eq_2 g_t4200E16C = 
	{
		0
	};
Eq_2 g_t4200E170 = 
	{
		0
	};
byte g_b4200E178 = 0x00;
struct Eq_120881 * g_ptr4200E17C = null;
byte g_b4200E184 = 0x00;
Eq_2 g_t4200E188 = 
	{
		0
	};
byte g_b4200E18C = 0x00;
struct Eq_129182 * g_ptr4200E194 = null;
byte g_b4200E198 = 0x00;
Eq_2 g_t4200E19C = 
	{
		0
	};
uint16 g_w4200E1A2 = 0x00;
struct Eq_105604 * g_ptr4200E1A8 = null;
Eq_2 g_t4200E1AC = 
	{
		0
	};
uint16 g_w4200E1B8 = 0x00;
Eq_2 g_t4200E1BC = 
	{
		0
	};
Eq_2 g_t4200E1C4 = 
	{
		0
	};
Eq_2 g_t4200E1C8 = 
	{
		0
	};
Eq_2 g_t4200E1D0 = 
	{
		0
	};
word32 g_dw4200E1D4 = 0x00;
int8 g_b4200E1D8 = 0;
byte g_b4200E1D9 = 0x00;
Eq_2 g_t4200E1DC = 
	{
		0
	};
Eq_191903 g_t4200E1E0 = 
	{
		0
	};
int32 g_dw4200E1E4 = 0;
Eq_192141 g_t4200E1E8 = 
	{
		0
	};
byte g_b4200E1EC = 0x00;
byte g_b4200E1ED = 0x00;
byte g_b4200E1EE = 0x00;
Eq_2 g_t4200E1F0 = 
	{
		0
	};
struct Eq_196992 * g_ptr4200E1F4 = null;
Eq_2 g_t4200E1F8 = 
	{
		0
	};
Eq_2 g_t4200E1FC = 
	{
		0
	};
Eq_2 g_t4200E200 = 
	{
		0
	};
Eq_2 g_t4200E204 = 
	{
		0
	};
Eq_2 g_t4200E20C = 
	{
		0
	};
Eq_2 g_t4200E210 = 
	{
		0
	};
Eq_2 g_t4200E218 = 
	{
		0
	};
struct Eq_201946 * g_ptr4200E21C = null;
Eq_2 g_t4200E220 = 
	{
		0
	};
Eq_2 g_t4200E224 = 
	{
		0
	};
Eq_2 g_t4200E228 = 
	{
		0
	};
int32 g_dw4200E22C = 0;
Eq_2 g_t4200E230 = 
	{
		0
	};
Eq_2 g_t4200E234 = 
	{
		0
	};
int32 g_dw4200E23C = 0;
word32 g_dw4200E240 = 0x00;
Eq_2 g_t4200E244 = 
	{
		0
	};
Eq_2 g_t4200E250 = 
	{
		0
	};
int32 g_dw4200E254 = 0;
Eq_2 g_t4200E258 = 
	{
		0
	};
Eq_2 g_t4200E25C = 
	{
		0
	};
Eq_2 g_t4200E260 = 
	{
		0
	};
word32 g_dw4200E264 = 0x00;
byte g_b4200E268 = 0x00;
int32 g_dw4200E26C = 0;
Eq_2 g_t4200E274 = 
	{
		0
	};
word32 ** g_ptr4200E278 = null;
Eq_2 g_t4200E280 = 
	{
		0
	};
Eq_2 g_t4200E284 = 
	{
		0
	};
int8 g_b4200E288 = 0;
int32 g_dw4200E28C = 0;
<anonymous> * g_ptr4200E290 = null;
word32 g_dw4200E294 = 0x00;
Eq_2 g_t4200E29C = 
	{
		0
	};
word32 g_a4200E2A0[] = 
	{
	};
int32 g_dw4200E2A4 = 0;
uint16 g_w4200E2A8 = 0x00;
Eq_2 g_t4200E2AC = 
	{
		0
	};
byte g_b4200E2B0 = 0x00;
byte g_b4200E2B8 = 0x00;
word32 g_dw4200E2BC = 0x00;
Eq_2 g_t4200E2C0 = 
	{
		0
	};
Eq_2 g_t4200E2C4 = 
	{
		0
	};
uint16 g_w4200E2C8 = 0x00;
Eq_2 g_t4200E2CC = 
	{
		0
	};
Eq_2 g_t4200E2D0 = 
	{
		0
	};
Eq_2 g_t4200E2D4 = 
	{
		0
	};
Eq_2 g_t4200E2D8 = 
	{
		0
	};
byte g_b4200E318 = 0x00;
struct Eq_232022 * g_ptr4200E31C = null;
byte g_b4200E320 = 0x00;
byte g_b4200E321 = 0x00;
Eq_2 g_t4200E324 = 
	{
		0
	};
byte g_b4200E328 = 0x00;
uint16 g_w4200E32A = 0x00;
struct Eq_242191 * g_ptr4200E32C = null;
byte g_b4200E330 = 0x00;
Eq_2 g_t4200E334 = 
	{
		0
	};
uint16 g_w4200E338 = 0x00;
Eq_2 g_t4200E33C = 
	{
		0
	};
uint16 g_w4200E340 = 0x00;
Eq_2 g_t4200E344 = 
	{
		0
	};
uint16 g_w4200E348 = 0x00;
uint16 g_w4200E34A = 0x00;
int32 g_dw4200E34C = 0;
Eq_2 g_t4200E354 = 
	{
		0
	};
uint16 g_w4200E358 = 0x00;
int32 g_dw4200E35C = 0;
Eq_2 g_t4200E364 = 
	{
		0
	};
byte g_b4200E368 = 0x00;
byte g_b4200E369 = 0x00;
byte g_b4200E374 = 0x00;
word32 g_dw4200E378 = 0x00;
byte g_b4200E380 = 0x00;
Eq_2 g_t4200E394 = 
	{
		0
	};
uint16 g_w4200E39C = 0x00;
byte g_b4200E3A0 = 0x00;
byte g_b4200E3A1 = 0x00;
word32 * g_ptr4200E3A4 = null;
Eq_319585 g_t4200E3A8 = 
	{
		0
	};
word32 * g_ptr4200E3AC = null;
word32 * g_ptr4200E3B0 = null;
int32 g_dw4200E3B8 = 0;
int32 g_dw4200E3BC = 0;
int32 g_dw4200E3C0 = 0;
ptr32 * g_ptr4200E3C4 = null;
Eq_317680 g_t4200E3C8 = 
	{
		0x00
	};
int32 g_dw4200E3CC = 0;
struct Eq_317722 * g_ptr4200E3D0 = null;
struct Eq_317627 * g_ptr4200E3D4 = null;
int32 g_dw4200E3D8 = 0;
struct Eq_317627 * g_ptr4200E3DC = null;
struct Eq_317722 * g_ptr4200E3E0 = null;
struct Eq_317627 * g_ptr4200E3E4 = null;
struct Eq_317627 * g_ptr4200E3E8 = null;
struct Eq_314839 * g_ptr4200E3EC = null;
int32 g_dw4200E3F0 = 0;
int32 g_dw4200E3F4 = 0;
int32 g_dw4200E3F8 = 0;
int32 g_dw4200E3FC = 0;
Eq_317704 g_t4200E400 = 
	{
		0
	};
int32 g_dw4200E404 = 0;
int32 g_dw4200E408 = 0;
int32 g_dw4200E40C = 0;
struct Eq_314839 * g_ptr4200E410 = null;
struct Eq_317722 * g_ptr4200E414 = null;
Eq_317680 g_t4200E418 = 
	{
		0x00
	};
int32 g_dw4200E41C = 0;
int32 g_dw4200E420 = 0;
int32 g_dw4200E424 = 0;
word32 * g_ptr4200E428 = null;
int32 g_dw4200E430 = 0;
Eq_40955 g_t4200E437 = 
	{
		0x00,
		0x00,
	};
word32 g_dw4200E438 = 0x00;
word32 g_dw4200E43C = 0x00;
int32 g_dw4200E440 = 0;
Eq_359646 g_t4200E444 = 
	{
		0
	};
int32 g_dw4200E448 = 0;
struct Eq_38861 * g_ptr4200EBA8 = null;
byte g_b4200EBB4 = 0x00;
byte g_b4200EBB5 = 0x00;
byte g_b4200EC64 = 0x00;
byte g_b4200EC65 = 0x00;
word16 g_w4200EC78 = 0x00;
word16 g_w4200EC7A = 0x00;
word16 g_w4200ECAE = 0x00;
byte g_b4200ECC0 = 0x00;
byte g_b4200EDD4 = 0x00;
ptr32 g_ptr4200FD0C = 0x00;
ptr32 g_ptr4200FE8C = 0x00;
ptr32 g_ptr420104CC = 0x00;
ptr32 g_ptr4201052C = 0x00;
Eq_7717 g_t4201078C = 
	{
		null,
		0x00,
		0x00,
		0x00,
		0x00,
		null,
	};
Eq_7839 g_t42010AAC = 
	{
		0,
		0x00,
	};
Eq_370525 g_a42010ABC[] = 
	{
	};
Eq_7839 g_t42010D04 = 
	{
		0,
		0x00,
	};
Eq_2 g_t42010F04 = 
	{
		0
	};
Eq_2 g_t42010F0C = 
	{
		0
	};
Eq_2 g_t42010F10 = 
	{
		0
	};
struct Eq_45109 * g_ptr42010F18 = null;
word32 g_dw42010F20 = 0x00;
word32 g_dw42010F28 = 0x00;
uint16 g_w42010F2E = 0x00;
word16 g_w42010F30 = 0x00;
struct Eq_67271 * g_ptr42010F34 = null;
byte g_b42010F3C = 0x00;
byte g_b42010F3D = 0x00;
byte g_b42011D3C = 0x00;
byte g_b42011D44 = 0x00;
uint16 g_w42011D46 = 0x00;
Eq_140777 g_t42011DBC = 
	{
		0
	};
byte g_b42011DC0 = 0x00;
byte g_b42011DC8 = 0x00;
uint16 g_w42011DCA = 0x00;
Eq_140777 g_t42011E40 = 
	{
		0
	};
word16 g_w42011E64 = 0x00;
word16 g_w42011E6A = 0x00;
byte g_b42011E6C = 0x00;
uint32 g_dw42011F24 = 0x00;
word32 g_dw420120D4 = 0x00;
uint16 g_w420120D8 = 0x00;
word32 g_dw42012100 = 0x00;
Eq_151434 g_t42012110 = 
	{
		0x00,
		0x00,
	};
word32 g_dw420121B0 = 0x00;
word32 g_dw420121B4 = 0x00;
word32 g_dw420121B8 = 0x00;
word32 g_dw420121BC = 0x00;
word32 g_dw420121C0 = 0x00;
word32 g_dw420121C4 = 0x00;
word32 g_dw420121C8 = 0x00;
word32 g_dw420121CC = 0x00;
word32 g_dw420121D0 = 0x00;
word32 g_dw420121D4 = 0x00;
Eq_152472 g_t420121D8 = 
	{
		0,
	};
uint16 g_w42012278 = 0x00;
byte g_b4201227A = 0x00;
byte g_b42012280 = 0x00;
byte g_b42012285 = 0x00;
Eq_151787 g_t420122AC = 
	{
		null,
	};
uint16 g_w42012318 = 0x00;
byte g_b4201231A = 0x00;
byte g_b42012320 = 0x00;
byte g_b42012325 = 0x00;
Eq_151787 g_t4201234C = 
	{
		null,
	};
Eq_160715 g_t42012650 = 
	{
		0x00,
	};
struct Eq_171128 * g_ptr420128B0 = null;
byte g_b42012AB8 = 0x00;
byte g_b42012AB9 = 0x00;
Eq_370779 g_a42012B50[] = 
	{
	};
Eq_370775 g_a42012BE8[] = 
	{
	};
Eq_370776 g_a42012BEC[] = 
	{
	};
Eq_370777 g_a42012BF0[] = 
	{
	};
Eq_202537 g_t42012C08 = 
	{
		0
	};
int32 g_dw42012EB0 = 0;
struct Eq_203424 * g_ptr42012EBC = null;
Eq_2 g_t42012EC4 = 
	{
		0
	};
Eq_2 g_t42012ED8 = 
	{
		0
	};
Eq_7717 g_t42012EEC = 
	{
		null,
		0x00,
		0x00,
		0x00,
		0x00,
		null,
	};
Eq_7717 g_t42012F54 = 
	{
		null,
		0x00,
		0x00,
		0x00,
		0x00,
		null,
	};
word32 g_a42012FC4[] = 
	{
	};
Eq_370747 g_a42013110[] = 
	{
	};
Eq_7717 g_t42013244 = 
	{
		null,
		0x00,
		0x00,
		0x00,
		0x00,
		null,
	};
byte g_b42013AB8 = 0x00;
int32 g_dw42014B14 = 0;
word32 g_dw42014FB4 = 0x00;
word32 g_dw42014FB8 = 0x00;
word32 g_dw42014FC4 = 0x00;
word32 g_dw42014FC8 = 0x00;
Eq_222978 g_t42014FE4 = 
	{
		0x00,
		0x00,
	};
Eq_370810 g_a42014FEC[5] = 
	{
		
		{
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
		},
	};
Eq_222978 g_t42015424 = 
	{
		0x00,
		0x00,
	};
word32 g_dw420155D8 = 0x00;
uint16 g_w420155E0 = 0x00;
struct Eq_241951 * g_ptr420155E8 = null;
Eq_306731 g_t42016380 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
	};
byte g_a42016484[15] = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_313390 g_t42016494 = 
	{
		0x00
	};
Eq_370926 g_a420164FC[5] = 
	{
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
		
		{
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
			0x00,
		},
	};
word16 g_w420166C4 = 0x00;
int32 g_dw420166E0 = 0;
struct Eq_21396 * g_ptr420166F0 = null;
byte g_b420166F8 = 0x00;
Eq_19851 g_t420166FC = 
	{
		0,
	};
uint16 g_a420169CC[] = 
	{
	};
word16 g_a420169CE[] = 
	{
	};
uint16 g_a42016A1C[22] = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
word32 * g_a42016A7C[15] = 
	{
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
	};
word32 * g_ptr42016A80 = null;
word32 * g_ptr42016A84 = null;
word32 * g_ptr42016A88 = null;
word32 * g_ptr42016A8C = null;
word32 * g_ptr42016A90 = null;
word32 * g_ptr42016A94 = null;
word32 * g_ptr42016A98 = null;
word32 * g_ptr42016A9C = null;
word32 * g_ptr42016AA0 = null;
word32 * g_ptr42016AA4 = null;
word32 * g_ptr42016AA8 = null;
word32 * g_ptr42016AAC = null;
word32 * g_ptr42016AB0 = null;
word32 * g_a42016AB4[15] = 
	{
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
	};
ptr32 g_ptr42016AEC = 0x00;
uint32 g_dw42016B00 = 0x00;
int32 g_dw42016B04 = 0;
int32 g_dw42016BA0 = 0;
int32 g_dw42016BCC = 0;
int32 g_dw42016BD0 = 0;
int32 g_dw42016BD4 = 0;
int32 g_dw42016BD8 = 0;
int32 g_dw42016C04 = 0;
int32 g_dw42016C08 = 0;
int32 g_dw42016C0C = 0;
int32 g_dw42016C10 = 0;
int32 g_dw42016C3C = 0;
int32 g_dw42016C40 = 0;
int32 g_dw42016C44 = 0;
int32 g_dw42016C48 = 0;
int32 g_dw42016C74 = 0;
int32 g_dw42016C78 = 0;
int32 g_dw42016C7C = 0;
int32 g_dw42016C80 = 0;
int32 g_dw42016CA8 = 0;
Eq_120471 g_t42016E6C = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_370946 g_a42016E7C[] = 
	{
	};
byte g_b42016F94 = 0x00;
byte g_b42016F95 = 0x00;
byte g_b42016F96 = 0x00;
Eq_2 g_t42016F98 = 
	{
		0
	};
byte g_b42016F9C = 0x00;
word32 g_dw42016FA4 = 0x00;
word32 g_dw42016FA8 = 0x00;
Eq_20960 g_t42017000 = 
	{
		0x00,
	};
word16 g_w42017002 = 0x00;
int8 g_b42017014 = 0;
word16 g_w42017072 = 0x00;
word32 g_dw42017074 = 0x00;
Eq_370530 g_a42017246[] = 
	{
	};
word16 g_w420179CC = 0x00;
Eq_370942 g_a42017E6C[] = 
	{
	};
word32 g_dw42017F98 = 0x00;
Eq_19782 g_t42017F9C = 
	{
		0,
	};
ui32 g_dw42017FA0 = 0x00;
Eq_2 g_t420186B4 = 
	{
		0
	};
uint16 g_w420186EC = 0x00;
byte g_b420186EE = 0x00;
Eq_21721 g_t42018750 = 
	{
		0x00,
	};
uint16 g_w42018756 = 0x00;
byte g_b42018758 = 0x00;
byte g_b4201875C = 0x00;
int32 g_dw42018760 = 0;
int32 g_dw42018764 = 0;
int32 g_dw42018768 = 0;
Eq_38361 g_t42018770 = 
	{
		
		{
			0
		},
		null,
		
		{
			0
		},
		0,
		0,
	};
<anonymous> * g_ptr42018798 = null;
Eq_32171 g_t42018AC8 = 
	{
		0x00
	};
word32 g_dw42018ACC = 0x00;
Eq_43031 g_t42019000 = 
	{
		
		{
			0
		},
	};
struct Eq_39121 * g_ptr42019598 = null;
word32 g_dw420195E0 = 0x00;
Eq_41225 g_t42019604 = 
	{
		0x00,
		0x00,
	};
Eq_2 g_t4201960C = 
	{
		0
	};
Eq_2 g_t42019610 = 
	{
		0
	};
<anonymous> * g_ptr42019624 = null;
<anonymous> * g_ptr42019628 = null;
<anonymous> * g_ptr42019634 = null;
<anonymous> * g_ptr42019638 = null;
<anonymous> * g_ptr42019640 = null;
byte g_b42019650 = 0x00;
byte g_a42019750[] = 
	{
	};
Eq_235270 g_t4201A000 = 
	{
		0x00
	};
Eq_2 g_t4201A004 = 
	{
		0
	};
Eq_2 g_t4201A00C = 
	{
		0
	};
struct Eq_235486 * g_ptr4201A074 = null;
word32 g_dw4201A078 = 0x00;
word32 g_dw4201A16C = 0x00;
word32 g_dw4201A19C = 0x00;
struct Eq_44866 * g_ptr4201A1A0 = null;
struct Eq_44866 * g_ptr4201A1A4 = null;
word32 g_dw4201A1A8 = 0x00;
Eq_2 g_t4201A1AC = 
	{
		0
	};
word32 g_dw4201A1B0 = 0x00;
int32 g_dw4201A1C0 = 0;
int32 g_dw4201A1C8 = 0;
Eq_370557 g_a4201A1D4[] = 
	{
	};
Eq_69224 g_t4201A1F4 = 
	{
		0x00,
	};
Eq_370566 g_a4201A21C[] = 
	{
	};
word32 g_dw4201A30C = 0x00;
word32 g_dw4201A314 = 0x00;
word32 g_dw4201A318 = 0x00;
byte g_b4201A31C = 0x00;
Eq_2 g_t4201A320 = 
	{
		0
	};
Eq_2 g_t4201A328 = 
	{
		0
	};
Eq_58417 g_t4201A330 = 
	{
		0
	};
int32 g_dw4201A348 = 0;
Eq_59372 g_t4201A350 = 
	{
		0x00
	};
byte g_b4201A352 = 0x00;
byte g_b4201A354 = 0x00;
byte g_b4201A355 = 0x00;
Eq_77909 g_t4201A358 = 
	{
		0x00,
	};
Eq_2 g_t4201A360 = 
	{
		0
	};
Eq_67452 g_t4201A368 = 
	{
		0x00
	};
struct Eq_58579 * g_ptr4201A36C = null;
Eq_2 g_t4201A370 = 
	{
		0
	};
uint16 g_w4201A378 = 0x00;
uint16 g_w4201A37A = 0x00;
uint16 g_w4201A37C = 0x00;
uint16 g_w4201A37E = 0x00;
uint16 g_w4201A380 = 0x00;
uint16 g_w4201A382 = 0x00;
int8 g_b4201A386 = 0;
int8 g_b4201A387 = 0;
int8 g_b4201A388 = 0;
byte g_b4201A389 = 0x00;
byte g_b4201A38F = 0x00;
byte g_b4201A398 = 0x00;
byte g_b4201A399 = 0x00;
struct Eq_71201 * g_ptr4201A3A0 = null;
byte g_b4201A3A4 = 0x00;
word16 g_w4201A3A6 = 0x00;
byte g_b4201A3A8 = 0x00;
struct Eq_71201 * g_ptr4201A3AC = null;
byte g_b4201A3B0 = 0x00;
Eq_67301 g_t4201A3B3 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_67301 g_t4201A3B9 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
uint16 g_w4201A3C4 = 0x00;
byte g_b4201A3C6 = 0x00;
byte g_b4201A3C7 = 0x00;
byte g_b4201A3C9 = 0x00;
byte g_b4201A3CA = 0x00;
byte g_b4201A42B = 0x00;
byte g_b4201A42C = 0x00;
word16 g_w4201A42E = 0x00;
word16 g_w4201A430 = 0x00;
uint16 g_w4201A434 = 0x00;
struct Eq_54618 * g_a4201A438[] = 
	{
	};
Eq_2 g_t4201A464 = 
	{
		0
	};
Eq_152619 g_t4201A470 = 
	{
		
		{
			0
		},
	};
struct Eq_149280 * g_ptr4201A4C8 = null;
Eq_2 g_t4201A4D4 = 
	{
		0
	};
byte g_b4201A4D8 = 0x00;
byte g_b4201A4D9 = 0x00;
byte g_b4201A4F8 = 0x00;
byte g_b4201A53C = 0x00;
byte g_b4201A53D = 0x00;
byte g_b4201A53E = 0x00;
byte g_b4201A558 = 0x00;
word32 g_dw4201A58C = 0x00;
word32 g_dw4201A590 = 0x00;
byte g_b4201A5BB = 0x00;
byte g_b4201A5BC = 0x00;
byte g_b4201A620 = 0x00;
byte g_b4201A621 = 0x00;
byte g_b4201A622 = 0x00;
byte g_b4201A623 = 0x00;
byte g_b4201A625 = 0x00;
byte g_b4201A626 = 0x00;
int32 g_dw4201A628 = 0;
byte g_b4201A62C = 0x00;
struct Eq_225905 * g_ptr4201A634 = null;
struct Eq_225897 * g_ptr4201A638 = null;
struct Eq_225922 * g_ptr4201A63C = null;
Eq_2 g_t4201A640 = 
	{
		0
	};
Eq_2 g_t4201A644 = 
	{
		0
	};
Eq_225879 g_t4201A650 = 
	{
		0x00,
	};
byte g_b4201A651 = 0x00;
byte g_b4201A652 = 0x00;
byte g_b4201A653 = 0x00;
byte g_b4201A654 = 0x00;
byte g_b4201A655 = 0x00;
byte g_b4201A656 = 0x00;
byte g_b4201A657 = 0x00;
byte g_b4201A658 = 0x00;
byte g_b4201A659 = 0x00;
Eq_2 g_t4201A65C = 
	{
		0
	};
Eq_2 g_t4201A660 = 
	{
		0
	};
byte g_b4201A664 = 0x00;
Eq_229240 g_t4201A668 = 
	{
		0x00,
	};
uint16 g_w4201A672 = 0x00;
uint16 g_w4201A682 = 0x00;
uint16 g_w4201A686 = 0x00;
uint16 g_w4201A68A = 0x00;
uint16 g_w4201A68C = 0x00;
uint16 g_w4201A690 = 0x00;
uint16 g_w4201A696 = 0x00;
uint16 g_w4201A698 = 0x00;
uint16 g_w4201A69A = 0x00;
uint16 g_w4201A69E = 0x00;
uint16 g_w4201A6A6 = 0x00;
uint16 g_w4201A6AC = 0x00;
uint16 g_w4201A6B0 = 0x00;
uint16 g_w4201A6B2 = 0x00;
uint16 g_w4201A6B6 = 0x00;
uint16 g_w4201A6C0 = 0x00;
uint16 g_w4201A6CA = 0x00;
uint16 g_w4201A6CC = 0x00;
uint16 g_w4201A6D4 = 0x00;
uint16 g_w4201A6D6 = 0x00;
uint16 g_w4201A6D8 = 0x00;
uint16 g_w4201A6DA = 0x00;
uint16 g_w4201A6DC = 0x00;
uint16 g_w4201A6E4 = 0x00;
uint16 g_w4201A6E6 = 0x00;
uint16 g_w4201A6EA = 0x00;
uint16 g_w4201A6EE = 0x00;
uint16 g_w4201A6F2 = 0x00;
uint16 g_w4201A6FA = 0x00;
uint16 g_w4201A6FC = 0x00;
uint16 g_w4201A6FE = 0x00;
uint16 g_w4201A702 = 0x00;
uint16 g_w4201A704 = 0x00;
uint16 g_w4201A706 = 0x00;
uint16 g_w4201A708 = 0x00;
uint16 g_w4201A70C = 0x00;
uint16 g_w4201A710 = 0x00;
uint16 g_w4201A712 = 0x00;
uint16 g_w4201A714 = 0x00;
word16 g_w4201A716 = 0x00;
uint16 g_w4201A718 = 0x00;
uint16 g_w4201A71A = 0x00;
uint16 g_w4201A71C = 0x00;
int32 g_a4201A720[] = 
	{
	};
uint16 * g_ptr4201A728 = null;
uint16 g_w4201A75C = 0x00;
uint16 g_w4201A760 = 0x00;
uint16 g_w4201A762 = 0x00;
uint16 g_w4201A764 = 0x00;
uint16 g_w4201A766 = 0x00;
uint16 g_w4201A768 = 0x00;
uint16 g_w4201A76A = 0x00;
uint16 g_w4201A76C = 0x00;
Eq_2 g_t4201A770 = 
	{
		0
	};
Eq_237624 g_t4201A774 = 
	{
		0x00
	};
Eq_2 g_t4201A778 = 
	{
		0
	};
Eq_2 g_t4201A77C = 
	{
		0
	};
Eq_2 g_t4201A780 = 
	{
		0
	};
byte g_b4201A784 = 0x00;
Eq_2 g_t4201A788 = 
	{
		0
	};
Eq_2 g_t4201A78C = 
	{
		0
	};
int32 g_dw4201A790 = 0;
Eq_2 g_t4201A794 = 
	{
		0
	};
struct Eq_226093 * g_ptr4201A798 = null;
Eq_2 g_t4201A79C = 
	{
		0
	};
Eq_2 g_t4201A7A4 = 
	{
		0
	};
Eq_2 g_t4201A7A8 = 
	{
		0
	};
Eq_2 g_t4201A7B0 = 
	{
		0
	};
Eq_250785 g_t4201A7B7 = 
	{
		null,
	};
byte g_b4201A7B8 = 0x00;
uint16 g_w4201A7BA = 0x00;
ui32 g_dw4201A7BC = 0x00;
byte g_b4201A7C0 = 0x00;
byte g_b4201A7D4 = 0x00;
byte g_b4201A7D5 = 0x00;
Eq_2 g_t4201A7D8 = 
	{
		0
	};
byte g_b4201A7DC = 0x00;
byte g_b4201A7DD = 0x00;
Eq_2 g_t4201A7E0 = 
	{
		0
	};
Eq_2 g_t4201A7E8 = 
	{
		0
	};
Eq_2 g_t4201A7F0 = 
	{
		0
	};
int32 g_dw4201A7F4 = 0;
Eq_2 g_t4201A7FC = 
	{
		0
	};
Eq_268388 g_t4201A800 = 
	{
		0x00,
		0x00,
	};
Eq_274487 g_t4201A808 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		
		{
			0x00
		},
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0,
		0x00,
		
		{
			0
		},
		0x00,
		0x00,
	};
byte g_a4201A9D2[] = 
	{
	};
uint16 g_a4201A9F0[] = 
	{
	};
struct Eq_290679 **** g_a4201AA64[] = 
	{
	};
Eq_2 g_a4201AAC8[] = 
	{
	};
uint16 g_w4201BC58 = 0x00;
word16 g_w4201BC5A = 0x00;
uint16 g_w4201BC5C = 0x00;
struct Eq_325731 * g_ptr4201BC88 = null;
byte g_a4201BC8D[] = 
	{
	};
Eq_370857 g_a4201BC90[] = 
	{
	};
byte g_b4201BCB0 = 0x00;
byte g_b4201BCB1 = 0x00;
int32 g_dw4201BCE0 = 0;
uint16 g_w4201BCE4 = 0x00;
byte g_b4201BCE6 = 0x00;
struct Eq_278301 * g_ptr4201BCE8 = null;
struct Eq_270754 * g_ptr4201BCF0 = null;
struct Eq_278728 g_t4201BCF8 = 
	{
		
		{
			0
		},
		0x00,
		
		{
			0
		},
		
		{
			0x00
		},
		0x00,
		0x00,
		0x00,
		
		{
			0x00
		},
	};
word32 g_dw4201BD24 = 0x00;
word32 g_dw4201BD28 = 0x00;
byte g_b4201BD4E = 0x00;
byte g_b4201BD51 = 0x00;
byte g_b4201BD52 = 0x00;
Eq_269045 g_t4201C000 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_2 g_t4201C06C = 
	{
		0
	};
Eq_325279 g_t4201C2D0 = 
	{
		?? /* Can't read address 840385C4 */
,
		
		{
			?? /* Can't read address 840385E0 */

		},
	};
word32 g_dw4201C2FC = 0x00;
word32 g_dw4201C300 = 0x00;
Eq_2 g_t4201C310 = 
	{
		0
	};
byte g_b4201C326 = 0x00;
int8 g_b4201C329 = 0;
byte g_b4201C32A = 0x00;
uint16 g_a4201C60E[] = 
	{
	};
struct Eq_284276 g_t4201C680 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		
		{
			0x00
		},
		
		{
			0
		},
		0x00,
		0x00,
		0x00,
		0x00,
		
		{
			?? /* Can't read address 84038CC8 */

		},
		?? /* Can't read address 84038CCC */
,
		?? /* Can't read address 84038CF0 */
,
		
		{
			?? /* Can't read address 84038CF4 */

		},
		?? /* Can't read address 84038CFC */
,
		?? /* Can't read address 84038CFE */
,
		?? /* Can't read address 84038D25 */
,
		?? /* Can't read address 84038D26 */
,
		?? /* Can't read address 84038D27 */
,
		?? /* Can't read address 84038D30 */
,
	};
word32 g_a4201C6B0[] = 
	{
	};
int32 g_dw4201C8A8 = 0;
Eq_2 g_t4201C8B0 = 
	{
		0
	};
byte g_b4201C8B8 = 0x00;
byte g_b4201C8B9 = 0x00;
byte g_b4201C8BA = 0x00;
Eq_285919 g_t4201C8BC = 
	{
		0x00,
	};
Eq_2 g_t4201C8C0 = 
	{
		0
	};
uint16 g_w4201C8C4 = 0x00;
Eq_337096 g_a4201C8C8[] = 
	{
	};
byte g_b4201C8CA = 0x00;
Eq_341716 g_t4201C8CB = 
	{
		0x00,
		0x00,
		0x00,
	};
uint16 g_w4201C8DC = 0x00;
byte g_b4201C8E4 = 0x00;
byte g_b4201C8EA = 0x00;
Eq_289282 g_t4201C8EC = 
	{
		0x00,
		0x00,
		0x00,
	};
Eq_289282 g_t4201C940 = 
	{
		0x00,
		0x00,
		0x00,
	};
byte g_b4201C9E8 = 0x00;
byte g_b4201C9E9 = 0x00;
byte g_b4201C9EA = 0x00;
byte g_b4201C9EB = 0x00;
byte g_b4201C9EC = 0x00;
byte g_b4201C9F1 = 0x00;
byte g_b4201C9F3 = 0x00;
byte g_b4201C9F4 = 0x00;
byte g_b4201C9F5 = 0x00;
Eq_2 g_t4201CADC = 
	{
		0
	};
uint16 g_w4201CAE0 = 0x00;
word16 g_w4201CAE2 = 0x00;
word16 g_w4201CAE4 = 0x00;
byte g_b4201CAE6 = 0x00;
byte g_b4201CAE7 = 0x00;
byte g_b4201CAE8 = 0x00;
byte g_b4201CAE9 = 0x00;
byte g_b4201CAEA = 0x00;
byte g_b4201CAEB = 0x00;
Eq_2 g_t4201CAF8 = 
	{
		0
	};
Eq_281611 g_t4201CB04 = 
	{
		0x00
	};
word16 g_w4201CB06 = 0x00;
word16 g_w4201CB08 = 0x00;
word16 g_w4201CB0A = 0x00;
word16 g_w4201CB0C = 0x00;
word16 g_w4201CB0E = 0x00;
byte g_b4201CB10 = 0x00;
byte g_b4201CB12 = 0x00;
Eq_268388 g_t4201CB18 = 
	{
		0x00,
		0x00,
	};
int32 g_dw4201CB20 = 0;
Eq_268388 g_t4201CB2C = 
	{
		0x00,
		0x00,
	};
Eq_268388 g_t4201CB34 = 
	{
		0x00,
		0x00,
	};
uint16 g_w4201CB42 = 0x00;
Eq_281736 g_t4201CB48 = 
	{
		0x00
	};
byte g_b4201CB49 = 0x00;
Eq_281752 g_t4201CB4A = 
	{
		0x00
	};
byte g_b4201CB4B = 0x00;
Eq_281768 g_t4201CB4C = 
	{
		0x00
	};
byte g_b4201CB4D = 0x00;
Eq_281800 g_t4201CB4E = 
	{
		0x00
	};
byte g_b4201CB4F = 0x00;
int32 g_dw4201CB58 = 0;
struct Eq_283764 * g_ptr4201CB5C = null;
word32 g_dw4201CB6C = 0x00;
word16 g_w4201CB70 = 0x00;
Eq_283682 g_t4201CB74 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		
		{
			0
		},
		0x00,
		0x00,
		0x00,
		0,
		0,
		0,
	};
Eq_370886 g_a4201CB7A[] = 
	{
	};
Eq_286033 g_t4201CCAC = 
	{
		0x00,
		0x00,
	};
uint16 g_w4201CCC4 = 0x00;
Eq_283358 g_t4201CCC6 = 
	{
		0x00
	};
byte g_b4201CCC7 = 0x00;
Eq_283858 g_t4201CCC8 = 
	{
		0
	};
byte g_b4201CCC9 = 0x00;
byte g_b4201CCCA = 0x00;
byte g_b4201CCCB = 0x00;
Eq_283898 g_t4201CCCC = 
	{
		0x00
	};
byte g_b4201CCCD = 0x00;
Eq_2 g_t4201CCF0 = 
	{
		0
	};
int32 g_dw4201CCF4 = 0;
Eq_268388 g_t4201CCF8 = 
	{
		0x00,
		0x00,
	};
byte g_b4201CD00 = 0x00;
byte g_b4201CD01 = 0x00;
struct Eq_292942 * g_ptr4201CD10 = null;
int32 g_dw4201CD14 = 0;
byte g_b4201CD1C = 0x00;
byte g_b4201CD24 = 0x00;
byte g_b4201CD25 = 0x00;
Eq_292339 g_t4201CD26 = 
	{
		0x00
	};
byte g_b4201CD27 = 0x00;
Eq_370909 g_a4201CD2E[] = 
	{
	};
byte g_a4201CD35[11] = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
word32 g_dw4201CD70 = 0x00;
word32 g_dw4201DADC = 0x00;
byte g_b4201DAEA = 0x00;
word16 g_w4201DB42 = 0x00;
Eq_2 g_t4201DB58 = 
	{
		0
	};
word32 g_dw4201DCF0 = 0x00;
word32 g_dw4201DD10 = 0x00;
Eq_325606 g_t4201E000 = 
	{
		
		{
			0
		},
	};
