// bl602_demo_at_bss_0001.c
// Generated by decompiling bl602_demo_at.elf
// using Reko decompiler version 0.9.3.0.

#include "bl602_demo_at.h"

Eq_578015 g_t4201F924 = 
	{
		0
	};
int32 g_dw4201F94C = 0;
word32 g_dw4201F984 = 0x00;
word16 g_w4201F996 = 0x00;
word16 g_w4201F9A4 = 0x00;
byte g_b4201F9B9 = 0x00;
ptr32 g_ptr4201F9FC = 0x00;
word32 g_dw4201FA08 = 0x00;
byte g_b4201FA53 = 0x00;
uint16 g_w4201FEB0 = 0x00;
word16 g_w4201FEB2 = 0x00;
uint16 g_w4201FEB4 = 0x00;
struct Eq_75288 * g_ptr4201FEE0 = null;
byte g_a4201FEE5[] = 
	{
	};
Eq_24073 g_t4201FEE8 = 
	{
		0x00,
		0x00,
	};
Eq_24073 g_t4201FEF0 = 
	{
		0x00,
		0x00,
	};
Eq_24073 g_t4201FEF8 = 
	{
		0x00,
		0x00,
	};
Eq_24073 g_t4201FF00 = 
	{
		0x00,
		0x00,
	};
Eq_24073 g_t4201FF08 = 
	{
		0x00,
		0x00,
	};
Eq_582516 g_a4201FF10[] = 
	{
	};
byte g_b4201FF30 = 0x00;
byte g_b4201FF31 = 0x00;
int32 g_dw4201FF60 = 0;
uint16 g_w4201FF64 = 0x00;
byte g_b4201FF66 = 0x00;
struct Eq_36092 * g_ptr4201FF68 = null;
Eq_2 g_t4201FF70 = 
	{
		0
	};
struct Eq_20979 g_t4201FF78 = 
	{
		0x00,
		0x00,
		0x00,
		0,
		0x00,
		0x00,
		?? /* Can't read address 8404051E */
,
		?? /* Can't read address 840408B0 */
,
		?? /* Can't read address 840408B1 */
,
	};
word32 g_dw4201FFA4 = 0x00;
word32 g_dw4201FFA8 = 0x00;
byte g_b4201FFCE = 0x00;
byte g_b4201FFD1 = 0x00;
byte g_b4201FFD2 = 0x00;
Eq_25912 g_t42020000 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_2 g_t4202006C = 
	{
		0
	};
Eq_74849 g_t42020550 = 
	{
		?? /* Can't read address 84040AC4 */
,
		
		{
			?? /* Can't read address 84040AE0 */

		},
	};
word32 g_dw4202057C = 0x00;
word32 g_dw42020580 = 0x00;
Eq_2 g_t42020590 = 
	{
		0
	};
byte g_b420205A6 = 0x00;
int8 g_b420205A9 = 0;
byte g_b420205AA = 0x00;
uint16 g_a4202088E[] = 
	{
	};
word32 g_a42020930[] = 
	{
	};
int32 g_dw42020B28 = 0;
Eq_2 g_t42020B30 = 
	{
		0
	};
byte g_b42020B38 = 0x00;
byte g_b42020B39 = 0x00;
byte g_b42020B3A = 0x00;
Eq_48311 g_t42020B3C = 
	{
		0x00,
	};
Eq_2 g_t42020B40 = 
	{
		0
	};
uint16 g_w42020B44 = 0x00;
Eq_82482 g_a42020B48[] = 
	{
	};
byte g_b42020B4A = 0x00;
Eq_38085 g_t42020B4B = 
	{
		0x00,
		0x00,
		0x00,
	};
uint16 g_w42020B5C = 0x00;
byte g_b42020B64 = 0x00;
byte g_b42020B6A = 0x00;
Eq_37241 g_t42020B6C = 
	{
		0x00,
	};
Eq_37241 g_t42020BC0 = 
	{
		0x00,
	};
byte g_b42020C68 = 0x00;
byte g_b42020C69 = 0x00;
byte g_b42020C6A = 0x00;
byte g_b42020C6B = 0x00;
byte g_b42020C6C = 0x00;
Eq_20710 g_t42021000 = 
	{
		?? /* Can't read address 650CE06C */
,
	};
Eq_57047 g_t42021004 = 
	{
		0x00
	};
byte g_b42021441 = 0x00;
byte g_b42021444 = 0x00;
Eq_2 g_t4202152C = 
	{
		0
	};
uint16 g_w42021530 = 0x00;
word16 g_w42021532 = 0x00;
word16 g_w42021534 = 0x00;
byte g_b42021536 = 0x00;
byte g_b42021537 = 0x00;
byte g_b42021538 = 0x00;
byte g_b42021539 = 0x00;
byte g_b4202153A = 0x00;
byte g_b4202153B = 0x00;
Eq_2 g_t42021548 = 
	{
		0
	};
Eq_43980 g_t42021554 = 
	{
		0x00
	};
word16 g_w42021556 = 0x00;
word16 g_w42021558 = 0x00;
word16 g_w4202155A = 0x00;
word16 g_w4202155C = 0x00;
word16 g_w4202155E = 0x00;
byte g_b42021560 = 0x00;
byte g_b42021562 = 0x00;
Eq_24073 g_t42021568 = 
	{
		0x00,
		0x00,
	};
int32 g_dw42021570 = 0;
Eq_24073 g_t4202157C = 
	{
		0x00,
		0x00,
	};
Eq_24073 g_t42021584 = 
	{
		0x00,
		0x00,
	};
uint16 g_w42021592 = 0x00;
Eq_44105 g_t42021598 = 
	{
		0x00
	};
byte g_b42021599 = 0x00;
Eq_44121 g_t4202159A = 
	{
		0x00
	};
byte g_b4202159B = 0x00;
Eq_44137 g_t4202159C = 
	{
		0x00
	};
byte g_b4202159D = 0x00;
Eq_44169 g_t4202159E = 
	{
		0x00
	};
byte g_b4202159F = 0x00;
int32 g_dw420215A8 = 0;
struct Eq_46156 * g_ptr420215AC = null;
word32 g_dw420215BC = 0x00;
word16 g_w420215C0 = 0x00;
Eq_46074 g_t420215C4 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		null,
		0x00,
		0x00,
		0x00,
		0,
		0,
		0,
	};
Eq_582558 g_a420215CA[] = 
	{
	};
Eq_48421 g_t420216FC = 
	{
		0x00,
		0x00,
	};
uint16 g_w42021714 = 0x00;
Eq_45767 g_t42021716 = 
	{
		0x00
	};
byte g_b42021717 = 0x00;
Eq_46250 g_t42021718 = 
	{
		0
	};
byte g_b42021719 = 0x00;
byte g_b4202171A = 0x00;
byte g_b4202171B = 0x00;
Eq_46290 g_t4202171C = 
	{
		0x00
	};
byte g_b4202171D = 0x00;
Eq_2 g_t42021740 = 
	{
		0
	};
int32 g_dw42021744 = 0;
Eq_24073 g_t42021748 = 
	{
		0x00,
		0x00,
	};
byte g_b42021750 = 0x00;
byte g_b42021751 = 0x00;
struct Eq_55191 * g_ptr42021760 = null;
int32 g_dw42021764 = 0;
byte g_b4202176C = 0x00;
byte g_b42021774 = 0x00;
byte g_b42021775 = 0x00;
Eq_54605 g_t42021776 = 
	{
		0x00
	};
byte g_b42021777 = 0x00;
Eq_582577 g_a4202177E[] = 
	{
	};
byte g_a42021785[11] = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_2 g_t420217C0 = 
	{
		0
	};
Eq_2 g_t420217C4 = 
	{
		0
	};
struct Eq_5817 * g_ptr420217C8 = null;
int32 g_dw420217CC = 0;
word32 g_dw420217D0 = 0x00;
word32 g_dw420217D4 = 0x00;
word32 g_dw420217D8 = 0x00;
struct Eq_58960 * g_ptr420217DC = null;
word32 g_dw420217E0 = 0x00;
Eq_2 g_t420217E4 = 
	{
		0
	};
word32 g_dw420217E8 = 0x00;
Eq_76495 g_t42022C84 = 
	{
		0x00,
	};
uint16 g_w42022C96 = 0x00;
byte g_b42022C9A = 0x00;
uint16 g_w42022CB2 = 0x00;
byte g_b42022CB6 = 0x00;
uint16 g_w42022CCE = 0x00;
byte g_b42022CD2 = 0x00;
Eq_75503 g_t42022CD8 = 
	{
		
		{
			0
		},
	};
byte g_b42022CDC = 0x00;
byte g_b42022CDD = 0x00;
word16 g_w42022CDE = 0x00;
word16 g_w42022CE0 = 0x00;
word16 g_w42022CE2 = 0x00;
byte g_b42022CE4 = 0x00;
word16 g_w42022CE6 = 0x00;
word16 g_w42022CEA = 0x00;
word16 g_w42022CEE = 0x00;
byte g_b42022CEF = 0x00;
byte g_b42022CF1 = 0x00;
Eq_75503 g_t42022CF4 = 
	{
		
		{
			0
		},
	};
byte g_b42022CF8 = 0x00;
byte g_b42022CF9 = 0x00;
word16 g_w42022CFA = 0x00;
word16 g_w42022CFC = 0x00;
word16 g_w42022CFE = 0x00;
byte g_b42022D00 = 0x00;
word16 g_w42022D02 = 0x00;
word16 g_w42022D06 = 0x00;
byte g_b42022D0A = 0x00;
byte g_b42022D0B = 0x00;
byte g_b42022D0D = 0x00;
Eq_75165 g_t42022D10 = 
	{
		
		{
			0
		},
	};
Eq_2 g_t42022D20 = 
	{
		0
	};
Eq_2 g_t42022D30 = 
	{
		0
	};
Eq_2 g_t42022D34 = 
	{
		0
	};
word32 g_dw42022D50 = 0x00;
int32 g_dw42022D78 = 0;
Eq_2 g_t42022D7C = 
	{
		0
	};
byte g_b42022D80 = 0x00;
byte g_b42022D81 = 0x00;
byte g_b42022D82 = 0x00;
byte g_b42022D83 = 0x00;
Eq_24073 g_t42022D84 = 
	{
		0x00,
		0x00,
	};
Eq_24073 g_t42022D8C = 
	{
		0x00,
		0x00,
	};
word16 g_w42022D9C = 0x00;
word16 g_w42022D9E = 0x00;
word32 g_dw42022E28 = 0x00;
word32 g_dw42022E48 = 0x00;
word32 g_dw42022E68 = 0x00;
word32 g_dw42022E88 = 0x00;
word32 g_dw42022EA8 = 0x00;
word32 g_dw42022EC8 = 0x00;
word32 g_dw42022EE8 = 0x00;
word32 g_dw42022F08 = 0x00;
word32 g_dw42022F28 = 0x00;
Eq_32746 g_t42022F48 = 
	{
		
		{
			0
		},
		0x00,
	};
Eq_80907 g_t42022FFC = 
	{
		0
	};
Eq_80910 g_t42023000 = 
	{
		0
	};
byte g_b42023030 = 0x00;
<anonymous> * g_ptr420230C8 = null;
Eq_99509 g_t420233F8 = 
	{
		0x00
	};
word32 g_dw420233FC = 0x00;
Eq_2 g_t42023D60 = 
	{
		0
	};
struct Eq_106418 * g_ptr42023EC8 = null;
Eq_96932 g_t42023F34 = 
	{
		
		{
			0
		},
		0x00,
	};
byte g_b42023F3C = 0x00;
word32 g_dw42023F44 = 0x00;
word32 g_dw42023F48 = 0x00;
word16 g_w42023FA2 = 0x00;
int8 g_b42023FB4 = 0;
byte g_b42023FBD = 0x00;
word16 g_w42023FBE = 0x00;
word16 g_w42023FC0 = 0x00;
byte g_b42023FC2 = 0x00;
ptr32 * g_ptr42023FDC = null;
ptr32 * g_ptr42023FE0 = null;
ptr32 * g_ptr42023FE4 = null;
Eq_113750 g_t42024000 = 
	{
		0x00,
	};
word16 g_w42024012 = 0x00;
word32 g_dw42024014 = 0x00;
Eq_582734 g_a420241E6[] = 
	{
	};
word32 g_dw42024EBC = 0x00;
word32 g_dw42024EC0 = 0x00;
word32 g_dw42024F10 = 0x00;
Eq_112633 g_t42024F3C = 
	{
		0,
	};
ui32 g_dw42024F40 = 0x00;
byte g_b42024FB4 = 0x00;
Eq_127261 g_t42025000 = 
	{
		
		{
			0
		},
	};
Eq_2 g_t42025654 = 
	{
		0
	};
uint16 g_w4202568C = 0x00;
byte g_b4202568E = 0x00;
Eq_114510 g_t420256F0 = 
	{
		0x00,
	};
uint16 g_w420256F6 = 0x00;
byte g_b420256F8 = 0x00;
byte g_b420256FC = 0x00;
int32 g_dw42025700 = 0;
int32 g_dw42025704 = 0;
int32 g_dw42025708 = 0;
Eq_2 g_t42025710 = 
	{
		0
	};
Eq_2 g_t42025714 = 
	{
		0
	};
Eq_2 g_t42025718 = 
	{
		0
	};
<anonymous> * g_ptr4202572C = null;
<anonymous> * g_ptr42025730 = null;
<anonymous> * g_ptr4202573C = null;
<anonymous> * g_ptr42025740 = null;
<anonymous> * g_ptr42025748 = null;
byte g_b42025758 = 0x00;
word32 g_dw42026000 = 0x00;
Eq_2 g_t42026004 = 
	{
		0
	};
word32 g_dw42026078 = 0x00;
word32 g_dw42026274 = 0x00;
word32 g_dw420262A4 = 0x00;
struct Eq_129045 * g_ptr420262A8 = null;
struct Eq_129045 * g_ptr420262AC = null;
word32 g_dw420262B0 = 0x00;
Eq_2 g_t420262B4 = 
	{
		0
	};
word32 g_dw420262B8 = 0x00;
int32 g_dw420262C8 = 0;
int32 g_dw420262D0 = 0;
Eq_582756 g_a420262DC[] = 
	{
	};
Eq_152986 g_t420262FC = 
	{
		0x00,
	};
Eq_582765 g_a42026324[] = 
	{
	};
word32 g_dw42026414 = 0x00;
word32 g_dw4202641C = 0x00;
word32 g_dw42026420 = 0x00;
byte g_b42026424 = 0x00;
Eq_2 g_t42026428 = 
	{
		0
	};
Eq_2 g_t42026430 = 
	{
		0
	};
Eq_142442 g_t42026438 = 
	{
		0
	};
int32 g_dw42026450 = 0;
Eq_143303 g_t42026458 = 
	{
		0x00
	};
byte g_b4202645A = 0x00;
byte g_b4202645C = 0x00;
byte g_b4202645D = 0x00;
Eq_161081 g_t42026460 = 
	{
		0x00,
	};
Eq_2 g_t42026468 = 
	{
		0
	};
Eq_151243 g_t42026470 = 
	{
		0x00
	};
struct Eq_142600 * g_ptr42026474 = null;
Eq_2 g_t42026478 = 
	{
		0
	};
uint16 g_w42026480 = 0x00;
uint16 g_w42026482 = 0x00;
uint16 g_w42026484 = 0x00;
uint16 g_w42026486 = 0x00;
uint16 g_w42026488 = 0x00;
uint16 g_w4202648A = 0x00;
int8 g_b4202648E = 0;
int8 g_b4202648F = 0;
int8 g_b42026490 = 0;
byte g_b42026491 = 0x00;
byte g_b42026497 = 0x00;
byte g_b420264A0 = 0x00;
byte g_b420264A1 = 0x00;
word16 g_w420264A4 = 0x00;
struct Eq_154950 * g_ptr420264A8 = null;
byte g_b420264AC = 0x00;
word16 g_w420264AE = 0x00;
byte g_b420264B0 = 0x00;
struct Eq_154950 * g_ptr420264B4 = null;
byte g_b420264B8 = 0x00;
Eq_151092 g_t420264BB = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
Eq_151092 g_t420264C1 = 
	{
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
		0x00,
	};
uint16 g_w420264CC = 0x00;
byte g_b420264CE = 0x00;
byte g_b420264CF = 0x00;
byte g_b420264D1 = 0x00;
byte g_b420264D2 = 0x00;
byte g_b42026533 = 0x00;
byte g_b42026534 = 0x00;
word16 g_w42026536 = 0x00;
word16 g_w42026538 = 0x00;
uint16 g_w4202653C = 0x00;
struct Eq_138804 * g_a42026540[] = 
	{
	};
struct Eq_192157 * g_ptr420265A0 = null;
Eq_2 g_t420265A4 = 
	{
		0
	};
Eq_187914 g_t420265A8 = 
	{
		0x00,
		
		{
			0
		},
		null,
		
		{
			0x00
		},
		
		{
			0
		},
		
		{
			0
		},
		
		{
			0x00
		},
	};
Eq_2 g_t42026610 = 
	{
		0
	};
int32 g_dw42026614 = 0;
Eq_2 g_t4202663C = 
	{
		0
	};
Eq_2 g_t42026640 = 
	{
		0
	};
int32 g_dw42026644 = 0;
byte g_b42026650 = 0x00;
byte g_b42026651 = 0x00;
byte g_b42026670 = 0x00;
byte g_b420266B4 = 0x00;
byte g_b420266B5 = 0x00;
byte g_b420266B6 = 0x00;
byte g_b420266B7 = 0x00;
byte g_b420266B8 = 0x00;
byte g_b420266D4 = 0x00;
byte g_a420266F0[] = 
	{
	};
byte g_b42026737 = 0x00;
byte g_b42026738 = 0x00;
byte g_b4202679C = 0x00;
byte g_b4202679E = 0x00;
byte g_b4202679F = 0x00;
byte g_b420267A0 = 0x00;
byte g_b420267A1 = 0x00;
byte g_b420267A3 = 0x00;
byte g_b420267A4 = 0x00;
byte g_b420267A5 = 0x00;
Eq_385116 g_t420267A8 = 
	{
		0
	};
int32 g_dw420267AC = 0;
int32 g_dw420267B0 = 0;
byte g_b420267B4 = 0x00;
struct Eq_392879 * g_ptr420267BC = null;
struct Eq_392871 * g_ptr420267C0 = null;
struct Eq_392896 * g_ptr420267C4 = null;
Eq_2 g_t420267C8 = 
	{
		0
	};
Eq_2 g_t420267CC = 
	{
		0
	};
Eq_392853 g_t420267D8 = 
	{
		0x00,
	};
byte g_b420267D9 = 0x00;
byte g_b420267DA = 0x00;
byte g_b420267DB = 0x00;
byte g_b420267DC = 0x00;
byte g_b420267DD = 0x00;
byte g_b420267DE = 0x00;
byte g_b420267DF = 0x00;
byte g_b420267E0 = 0x00;
byte g_b420267E1 = 0x00;
Eq_2 g_t420267E4 = 
	{
		0
	};
Eq_2 g_t420267E8 = 
	{
		0
	};
byte g_b420267EC = 0x00;
Eq_396246 g_t420267F0 = 
	{
		0x00,
	};
uint16 g_w420267FA = 0x00;
uint16 g_w4202680A = 0x00;
uint16 g_w4202680E = 0x00;
uint16 g_w42026812 = 0x00;
uint16 g_w42026814 = 0x00;
uint16 g_w42026818 = 0x00;
uint16 g_w4202681E = 0x00;
uint16 g_w42026820 = 0x00;
uint16 g_w42026822 = 0x00;
uint16 g_w42026826 = 0x00;
uint16 g_w4202682E = 0x00;
uint16 g_w42026834 = 0x00;
uint16 g_w42026838 = 0x00;
uint16 g_w4202683A = 0x00;
uint16 g_w4202683E = 0x00;
uint16 g_w42026848 = 0x00;
uint16 g_w42026852 = 0x00;
uint16 g_w42026854 = 0x00;
uint16 g_w4202685C = 0x00;
uint16 g_w4202685E = 0x00;
uint16 g_w42026860 = 0x00;
uint16 g_w42026862 = 0x00;
uint16 g_w42026864 = 0x00;
uint16 g_w42026866 = 0x00;
uint16 g_w42026868 = 0x00;
uint16 g_w4202686C = 0x00;
uint16 g_w4202686E = 0x00;
uint16 g_w42026872 = 0x00;
uint16 g_w42026876 = 0x00;
uint16 g_w4202687A = 0x00;
uint16 g_w42026882 = 0x00;
uint16 g_w42026884 = 0x00;
uint16 g_w42026886 = 0x00;
uint16 g_w4202688A = 0x00;
uint16 g_w4202688C = 0x00;
uint16 g_w4202688E = 0x00;
uint16 g_w42026890 = 0x00;
uint16 g_w42026894 = 0x00;
uint16 g_w42026898 = 0x00;
uint16 g_w4202689A = 0x00;
uint16 g_w4202689C = 0x00;
uint16 g_w420268A0 = 0x00;
uint16 g_w420268A2 = 0x00;
uint16 g_w420268A4 = 0x00;
int32 g_a420268A8[] = 
	{
	};
uint16 * g_ptr420268B0 = null;
uint16 g_w420268E4 = 0x00;
uint16 g_w420268E8 = 0x00;
uint16 g_w420268EA = 0x00;
uint16 g_w420268EC = 0x00;
uint16 g_w420268EE = 0x00;
uint16 g_w420268F0 = 0x00;
uint16 g_w420268F2 = 0x00;
uint16 g_w420268F4 = 0x00;
Eq_2 g_t420268F8 = 
	{
		0
	};
Eq_406632 g_t420268FC = 
	{
		0x00
	};
Eq_2 g_t42026900 = 
	{
		0
	};
Eq_2 g_t42026904 = 
	{
		0
	};
Eq_2 g_t42026908 = 
	{
		0
	};
Eq_2 g_t42026910 = 
	{
		0
	};
Eq_2 g_t42026914 = 
	{
		0
	};
Eq_2 g_t42026918 = 
	{
		0
	};
struct Eq_393067 * g_ptr4202691C = null;
Eq_2 g_t42026920 = 
	{
		0
	};
Eq_2 g_t42026928 = 
	{
		0
	};
Eq_2 g_t4202692C = 
	{
		0
	};
Eq_2 g_t42026930 = 
	{
		0
	};
uint16 g_w42027000 = 0x00;
Eq_2 g_t4202700C = 
	{
		0
	};
struct Eq_403124 * g_ptr42027074 = null;
word32 g_dw420277A8 = 0x00;
Eq_421201 g_t420277B7 = 
	{
		null,
	};
word16 g_w4202789E = 0x00;
Eq_2 g_t420278F8 = 
	{
		0
	};
int32 g_dw420278FC = 0;
Eq_2 g_t42027900 = 
	{
		0
	};
Eq_2 g_t42027904 = 
	{
		0
	};
Eq_2 g_t42027908 = 
	{
		0
	};
byte g_b4202790C = 0x00;
Eq_2 g_t42027914 = 
	{
		0
	};
word32 g_dw42027930 = 0x00;
<anonymous> * g_ptr42027944 = null;
<anonymous> * g_ptr42027948 = null;
ptr32 g_ptr42027E64 = 0x00;
Eq_123468 g_t42028000 = 
	{
		0x00,
		
		{
			0
		},
		?? /* Can't read address 42028100 */
,
		?? /* Can't read address 42028718 */
,
	};
Eq_2 g_t420280E8 = 
	{
		0
	};
Eq_2 g_t420280EC = 
	{
		0
	};
byte g_b420280F2 = 0x00;
