// bl602_demo_at_boot2.c
// Generated by decompiling bl602_demo_at.elf
// using Reko decompiler version 0.9.3.0.

#include "bl602_demo_at.h"

byte g_b4200EFA8 = 0x00;
int32 g_dw4200EFAC = 0;
uint16 g_w4200EFB2 = 0x00;
Eq_374387 g_a4200EFB8[] = 
	{
	};
Eq_2 g_t4200F000 = 
	{
		0
	};
int32 * g_ptr4200F004 = null;
Eq_2 g_t4200F018 = 
	{
		0
	};
Eq_361368 g_t4200F044 = 
	{
		0x00
	};
word32 g_dw4200F200 = 0x00;
byte g_b4200F211 = 0x00;
