void rf_pri_auto_gain(void);
void rf_pri_chipv(uint8_t chipv);
void rf_pri_config_bandwidth(uint32_t bw);
void rf_pri_config_channel(uint32_t channel_index);
void rf_pri_config_mode(uint32_t mode);
void rf_pri_config_txgain(uint32_t gc_tbb_boost, uint32_t gc_tmx, uint32_t gc_tbb);
void rf_pri_fcal(void);
uint16_t rf_pri_fcal_meas(uint32_t cw);
void rf_pri_fixed_val_regs(void);
void rf_pri_full_cal(void);
void rf_pri_get_notch_param(uint32_t chanfreq_MHz, uint8_t * ncf_on, int32_t * ncf_freq_Hz);
uint32_t rf_pri_get_txgain_index(int32_t pwr, uint32_t mode);
int32_t rf_pri_get_txgain_max(void);
int32_t rf_pri_get_txgain_min(void);
uint32_t rf_pri_get_vco_freq_cw(uint32_t chanfreq_MHz);
uint32_t rf_pri_get_vco_idac_cw(uint32_t chanfreq_MHz);
void rf_pri_init(uint8_t reset, uint8_t chipv);
void rf_pri_init_fast(uint32_t flag);
void rf_pri_lo_acal(void);
void rf_pri_manu_pu(uint32_t mode);
uint32_t rf_pri_pm_pwr(void);
int32_t rf_pri_pm_pwr_avg(uint32_t iq, uint32_t acc_len);
void rf_pri_query_txgain_table(uint32_t index, uint32_t * rfg_index, uint32_t * dg);
void rf_pri_rccal(void);
void rf_pri_rccal_config(uint32_t iq, uint32_t rbb_fc);
uint32_t rf_pri_rccal_iq(uint32_t iq);
void rf_pri_restore_cal_reg(void);
void rf_pri_restore_state_for_cal(void);
void rf_pri_roscal(void);
void rf_pri_roscal_config(uint32_t iq, uint32_t rosdac);
uint32_t rf_pri_roscal_iq(uint32_t iq, uint32_t length, uint32_t sram_start_addr);
void rf_pri_save_state_for_cal(void);
void rf_pri_set_gain_table_regs(void);
void rf_pri_singen_amplitude(uint32_t gain_i, uint32_t gain_q);
void rf_pri_singen_config(uint32_t fcw, uint32_t start_addr_q, uint32_t start_addr_i);
void rf_pri_singen_pwrmx_dc(uint32_t amp, uint32_t num_data, int32_t adc_mean_max, int32_t adc_mean_min);
void rf_pri_singen_start(void);
void rf_pri_start_rxdfe(void);
void rf_pri_start_txdfe(void);
void rf_pri_stop_rxdfe(void);
void rf_pri_stop_txdfe(void);
void rf_pri_tx_gain_comp(int32_t Tsens);
void rf_pri_txcal(void);
void rf_pri_txcal_config(uint32_t param_ind, int32_t val);
void rf_pri_txcal_config_hw(void);
int32_t rf_pri_txcal_search_core(uint32_t param_ind, uint32_t center, uint32_t delta, uint32_t meas_freq);
void rf_pri_update_dvga_os(int8_t dvga_os);
void rf_pri_update_param(uint32_t chanfreq_MHz);
void rf_pri_update_power_offset(int32_t * power_offset);
void rf_pri_update_tx_power_offset(uint8_t channel, int8_t * power_offset);
void rf_pri_update_txgain_tempos(int16_t tempos);
void rf_pri_wait_ms(uint32_t ms);
void rf_pri_wait_us(uint32_t us);
void rf_pri_xtalfreq(uint32_t xtalfreq);
void rfc_apply_tx_dvga(void);
