void coex_wifi_pta_forece_enable(int );
void GLB_Set_WiFi_Core_CLK(uint8_t );
void _check_chip_status(void);
void _dac_check(void);
void _ir_check(void);
void _reset_all_except_uart_gpio(void);
void AON_LowPower_Enter_PDS0(void);
void AON_LowPower_Exit_PDS0(void);
void assert_err(char * condition, char * file, int line);
void assert_rec(char * condition, char * file, int line);
void assert_warn(char * condition, char * file, int line);
void coex_dump_pta_enable(void);
void coex_dump_wifi_cntl(void);
void coex_dump_wifi_pti(void);
void coex_dump_wifi_status(void);
void coex_wifi_pta_forece_enable(int enable);
void coex_wifi_pti_forece_enable(int enable);
void coex_wifi_rf_forece_enable(int enable);
void force_trigger(char * msg);
void wifi_main(void * param);
