
void rf_adc_clk_div_sel_setf(uint32_t x);
void rf_bbmode_4s_en_setf(uint32_t x);
void rf_bbmode_4s_setf(uint32_t x);
void rf_ch_ind_wifi_setf(uint32_t x);
void rf_dac_bias_sel_setf(uint32_t x);
void rf_fsm_ctrl_en_setf(uint32_t x);
void rf_fsm_lo_rdy_rst_setf(uint32_t x);
void rf_fsm_lo_time_setf(uint32_t x);
void rf_fsm_st_dbg_en_setf(uint32_t x);
void rf_fsm_st_dbg_setf(uint32_t x);
void rf_fsm_t2r_cal_mode_setf(uint32_t x);
void rf_gc_tbb_boost_setf(uint32_t x);
void rf_gc_tbb_setf(uint32_t x);
void rf_gc_tmx_setf(uint32_t x);
void rf_lo_center_freq_mhz_setf(uint32_t x);
void rf_lo_ctrl_hw_setf(uint32_t x);
void rf_lo_fbdv_rst_setf(uint32_t x);
void rf_lo_osmx_cap_setf(uint32_t x);
void rf_lo_pfd_rst_csd_setf(uint32_t x);
void rf_lo_sdm_bypass_setf(uint32_t x);
void rf_lo_sdmin_1m_setf(uint32_t x);
void rf_lo_sdmin_center_setf(uint32_t x);
void rf_lo_sdmin_if_setf(uint32_t x);
void rf_lo_sdmin_setf(uint32_t x);
uint32_t rf_lo_unlocked_getf(void);
void rf_lo_vco_freq_cw_setf(uint32_t x);
void rf_lo_vco_idac_cw_setf(uint32_t x);
void rf_pa_etb_en_setf(uint32_t x);
void rf_pa_half_on_setf(uint32_t x);
void rf_pa_ib_fix_setf(uint32_t x);
void rf_pa_iet_11b_setf(uint32_t x);
void rf_pa_iet_11g_setf(uint32_t x);
void rf_pa_iet_11n_setf(uint32_t x);
void rf_pa_iet_setf(uint32_t x);
void rf_pa_vbcas_11b_setf(uint32_t x);
void rf_pa_vbcas_11g_setf(uint32_t x);
void rf_pa_vbcas_11n_setf(uint32_t x);
void rf_pa_vbcas_setf(uint32_t x);
void rf_pa_vbcore_11b_setf(uint32_t x);
void rf_pa_vbcore_11g_setf(uint32_t x);
void rf_pa_vbcore_11n_setf(uint32_t x);
void rf_pa_vbcore_setf(uint32_t x);
void rf_pu_ctrl_hw_setf(uint32_t x);
void rf_pu_fbdv_setf(uint32_t x);
void rf_pu_osmx_setf(uint32_t x);
void rf_pu_pfd_setf(uint32_t x);
void rf_pu_vco_setf(uint32_t x);
void rf_rbb_bw_setf(uint32_t x);
void rf_rc_state_dbg_en_setf(uint32_t x);
void rf_rc_state_dbg_setf(uint32_t x);
void rf_rmxgm_10m_mode_en_setf(uint32_t x);
void rf_rx_adc_iq_swap_setf(uint32_t x);
void rf_rx_adc_os_i_setf(uint32_t x);
void rf_rx_adc_os_q_setf(uint32_t x);
void rf_rx_dfe_en_4s_en_setf(uint32_t x);
void rf_rx_dfe_en_4s_setf(uint32_t x);
void rf_rx_gain_ctrl_hw_setf(uint32_t x);
void rf_rx_iqc_gain_en_setf(uint32_t x);
void rf_rx_iqc_gain_setf(uint32_t x);
void rf_rx_iqc_phase_en_setf(uint32_t x);
void rf_rx_iqc_phase_setf(uint32_t x);
void rf_rx_notch0_alpha_setf(uint32_t x);
void rf_rx_notch0_en_setf(uint32_t x);
void rf_rx_notch0_nrmfc_setf(uint32_t x);
void rf_rx_notch1_alpha_setf(uint32_t x);
void rf_rx_notch1_en_setf(uint32_t x);
void rf_rx_notch1_nrmfc_setf(uint32_t x);
void rf_rx_pm_acc_len_setf(uint32_t x);
void rf_rx_pm_en_setf(uint32_t x);
void rf_rx_pm_freqshift_cw_setf(uint32_t x);
void rf_rx_pm_freqshift_en_setf(uint32_t x);
void rf_rx_pm_in_sel_setf(uint32_t x);
uint32_t rf_rx_pm_iqacc_i_getf(void);
uint32_t rf_rx_pm_iqacc_q_getf(void);
void rf_rx_pm_start_ofs_setf(uint32_t x);
void rf_sdm_ctrl_hw_setf(uint32_t x);
void rf_singen_clkdiv_n_setf(uint32_t x);
void rf_singen_en_setf(uint32_t x);
void rf_singen_gain_i_setf(uint32_t x);
void rf_singen_gain_q_setf(uint32_t x);
void rf_singen_inc_step0_setf(uint32_t x);
void rf_singen_mode_i_setf(uint32_t x);
void rf_singen_mode_q_setf(uint32_t x);
void rf_singen_start_addr0_i_setf(uint32_t x);
void rf_singen_start_addr0_q_setf(uint32_t x);
void rf_tbb_ind_gc0_setf(uint32_t x);
void rf_tbb_ind_gc10_setf(uint32_t x);
void rf_tbb_ind_gc11_setf(uint32_t x);
void rf_tbb_ind_gc12_setf(uint32_t x);
void rf_tbb_ind_gc13_setf(uint32_t x);
void rf_tbb_ind_gc14_setf(uint32_t x);
void rf_tbb_ind_gc15_setf(uint32_t x);
void rf_tbb_ind_gc1_setf(uint32_t x);
void rf_tbb_ind_gc2_setf(uint32_t x);
void rf_tbb_ind_gc3_setf(uint32_t x);
void rf_tbb_ind_gc4_setf(uint32_t x);
void rf_tbb_ind_gc5_setf(uint32_t x);
void rf_tbb_ind_gc6_setf(uint32_t x);
void rf_tbb_ind_gc7_setf(uint32_t x);
void rf_tbb_ind_gc8_setf(uint32_t x);
void rf_tbb_ind_gc9_setf(uint32_t x);
uint32_t rf_test_read_getf(void);
void rf_test_sel_setf(uint32_t x);
void rf_tmx_cs_setf(uint32_t x);
void rf_trxcal_ctrl_hw_setf(uint32_t x);
void rf_tx_dac_iq_swap_setf(uint32_t x);
void rf_tx_dac_os_i_setf(uint32_t x);
void rf_tx_dac_os_q_setf(uint32_t x);
void rf_tx_dfe_en_4s_en_setf(uint32_t x);
void rf_tx_dfe_en_4s_setf(uint32_t x);
void rf_tx_dvga_gain_ctrl_hw_setf(uint32_t x);
void rf_tx_dvga_gain_qdb_ble_gc0_setf(uint32_t x);
void rf_tx_dvga_gain_qdb_ble_gc1_setf(uint32_t x);
void rf_tx_dvga_gain_qdb_ble_gc2_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc0_getf(void);
void rf_tx_dvga_gain_qdb_gc0_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc10_getf(void);
void rf_tx_dvga_gain_qdb_gc10_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc11_getf(void);
void rf_tx_dvga_gain_qdb_gc11_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc12_getf(void);
void rf_tx_dvga_gain_qdb_gc12_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc13_getf(void);
void rf_tx_dvga_gain_qdb_gc13_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc14_getf(void);
void rf_tx_dvga_gain_qdb_gc14_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc15_getf(void);
void rf_tx_dvga_gain_qdb_gc15_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc1_getf(void);
void rf_tx_dvga_gain_qdb_gc1_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc2_getf(void);
void rf_tx_dvga_gain_qdb_gc2_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc3_getf(void);
void rf_tx_dvga_gain_qdb_gc3_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc4_getf(void);
void rf_tx_dvga_gain_qdb_gc4_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc5_getf(void);
void rf_tx_dvga_gain_qdb_gc5_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc6_getf(void);
void rf_tx_dvga_gain_qdb_gc6_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc7_getf(void);
void rf_tx_dvga_gain_qdb_gc7_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc8_getf(void);
void rf_tx_dvga_gain_qdb_gc8_setf(uint32_t x);
uint32_t rf_tx_dvga_gain_qdb_gc9_getf(void);
void rf_tx_dvga_gain_qdb_gc9_setf(uint32_t x);
void rf_tx_dvga_gain_qdb_setf(uint32_t x);
void rf_tx_gain_ctrl_hw_setf(uint32_t x);
void rf_tx_iqc_gain_en_setf(uint32_t x);
void rf_tx_iqc_gain_setf(uint32_t x);
void rf_tx_iqc_phase_en_setf(uint32_t x);
void rf_tx_iqc_phase_setf(uint32_t x);
void rf_tx_test_sel_setf(uint32_t x);
void rf_wifimode_4s_en_setf(uint32_t x);
void rf_wifimode_4s_setf(uint32_t x);
void rfckg_rxclk_div2_mode_setf(uint32_t x);
void rfif_int_lo_unlocked_mask_setf(uint32_t x);
